### ISSUE TITLE
NodeMailer attachments support

### ISSUE THREAD

**Issue by scopsy** [notifirehq/notifire#100]
## What?
Add support for sending attachments for our [NodeMailer](https://github.com/notifirehq/notifire/tree/master/providers/nodemailer) provider.

### Why?
To have the ability to use send attachments.

### How?
Based on Notifire IAttachmentOptions interface found [here](https://github.com/notifirehq/notifire/blob/master/packages/core/src/lib/template/template.interface.ts).
And NodeMailer methods found [here](https://nodemailer.com/message/attachments/)

### Usage
Based on Notifire IAttachmentOptions interface on the trigger.

**Comment by davidsoderberg** [comment]
Assign me :)

**Comment by galezra** [comment]
I'll handle it
