### ISSUE TITLE
Mailjet attachments support

### ISSUE THREAD

**Issue by scopsy** [notifirehq/notifire#101]
## What?
Add support for sending attachments for our [Mailjet](https://github.com/notifirehq/notifire/tree/master/providers/mailjet) provider.

### Why?
To have the ability to use send attachments.

### How?
Based on Notifire IAttachmentOptions interface found [here](https://github.com/notifirehq/notifire/blob/master/packages/core/src/lib/template/template.interface.ts).
And Mailjet method found [here](https://dev.mailjet.com/email/guides/send-api-V3/#send-with-attached-files)

### Usage
Based on Notifire IAttachmentOptions interface on the trigger.

**Comment by devblin** [comment]
Hey, I would like to work on this issue.

**Comment by scopsy** [comment]
@devblin Sure! Assigned you. Create your branch from the v0.3.0 branch to get the attachment interface

**Comment by ComBarnea** [comment]
Just in case that helps, 
### How to send single/multiple and inline with Mailjet
<img width="983" alt="Screen Shot 2021-11-13 at 11 27 52" src="https://user-images.githubusercontent.com/8877285/141613717-45b89618-ddad-455d-a828-869440cc089c.png">

**Comment by devblin** [comment]
Hey, so for inline-attachments there is no `inline-attachment` attribute in `IEmailOptions` interface, so we need to update this https://github.com/notifirehq/notifire/blob/725e5d279ce5ab6f1a85aaefe190db528fda3054/packages/core/src/lib/provider/provider.interface.ts#L11 
And, also in given attachment interface, we need to add `id` attribute as for mailjet-inline-attachments there is optional parameter `ContentID`
 https://github.com/notifirehq/notifire/blob/725e5d279ce5ab6f1a85aaefe190db528fda3054/packages/core/src/lib/template/template.interface.ts#L43

**Comment by scopsy** [comment]
@devblin for now let's leave the inline attachments out of the scope of this issue and just focus on regular attachments.
