### ISSUE TITLE
Mandrill attachments support

### ISSUE THREAD

**Issue by scopsy** [notifirehq/notifire#102]
## What?
Add support for sending attachments for our [Mandrill](https://github.com/notifirehq/notifire/tree/master/providers/mandrill) provider.

### Why?
To have the ability to use send attachments.

### How?
Based on Notifire IAttachmentOptions interface found [here](https://github.com/notifirehq/notifire/blob/master/packages/core/src/lib/template/template.interface.ts).
And Mandrill methods found [here](https://mailchimp.com/developer/transactional/api/messages/send-new-message/)

### Usage
Based on Notifire IAttachmentOptions interface on the trigger.

**Comment by ComBarnea** [comment]
See relevant attachment options at Mandrill site

### Full options for single/multiple and inline
<img width="496" alt="Screen Shot 2021-11-13 at 11 38 07" src="https://user-images.githubusercontent.com/8877285/141614052-86073e38-8543-4698-9e50-6b1dbff64142.png">

**Comment by diganta413** [comment]
Can I try out this issue?

**Comment by scopsy** [comment]
@diganta413 Sure! Assigning you

**Comment by scopsy** [comment]
@diganta413 Create your branch from the `v0.3.0` branch so you can get the new attachments interface

**Comment by diganta413** [comment]
@scopsy in mandrill.interface.ts, do I have to make a new attachment interface or I can simply import it?

**Comment by scopsy** [comment]
@diganta413 so sorry, just seen the message. There is already a provider you need to import it. All of the code is inside the `v0.3.0` branch. just merge from there.

Sorry for the delay :(
