### ISSUE TITLE
@notifire/core on npm is missing a readme.md

### ISSUE THREAD

**Issue by scopsy** [notifirehq/notifire#105]
### What?
When visiting the [@notifire/core](https://www.npmjs.com/package/@notifire/core) on npm a readme.md is missing.

We should add a step to the publish script to copy the root readme.md file to `packages/core` to keep them consisten

**Comment by SachinHatikankar100** [comment]
Hi @scopsy would like to fix this bug. Will let you know at the earliest if any issues or I am not able to fix it 👍

**Comment by SachinHatikankar100** [comment]
Hi @scopsy would like to fix this bug. Will let you know at the earliest if any issues or I am not able to fix it 👍

**Comment by scopsy** [comment]
Thank you @SachinHatikankar100 really appreciate it!

**Comment by scopsy** [comment]
Nest.js doing something similar with `npm prerelease` hook https://github.com/nestjs/nest/blob/master/tools/gulp/tasks/copy-misc.ts

They use gulp, which we don't but I believe just running some shell script or `cp` will work as npm script.

**Comment by SachinHatikankar100** [comment]
Hi @scopsy thanks for the details. I am just going through the details shared. Will get in touch if I require assistance 🙂

**Comment by SachinHatikankar100** [comment]
Hi @scopsy Need guidance. I found this link

https://stackoverflow.com/questions/30076596/add-readme-md-to-published-npm-package

Please let me know if this is something I can do to achieve my task?

**Comment by scopsy** [comment]
Pinged you discord, let me know if you need more help 🙌🚀
