### ISSUE TITLE
Email.js attachments support

### ISSUE THREAD

**Issue by scopsy** [notifirehq/notifire#109]
## What?
Add support for sending attachments for our [Email.js](https://github.com/notifirehq/notifire/tree/master/providers/emailjs) provider.

### Why?
To have the ability to use send attachments.

### How?
Based on Notifire IAttachmentOptions interface found [here](https://github.com/notifirehq/notifire/blob/master/packages/core/src/lib/template/template.interface.ts).
And Email.js methods found [here](https://github.com/eleith/emailjs)

### Usage
Based on Notifire IAttachmentOptions interface on the trigger.

**Comment by ComBarnea** [comment]
See relevant attachment options at Email.js site

### Full options for single/multiple and inline
<img width="880" alt="Screen Shot 2021-11-20 at 10 35 08" src="https://user-images.githubusercontent.com/8877285/142720018-f2928e09-66a3-4d20-9549-1281510f304c.png">

**Comment by peoray** [comment]
Hiii 👋🏽. I'm interested in this project and would love to kick things off by contributing to this issue :)

**Comment by scopsy** [comment]
@peoray Hi!!! so nice to meet you! Sure Assigned you.

Create your branch out of `v0.3.0` so you'll have the attachments interface 🙌
