### ISSUE TITLE
Theming API

### ISSUE THREAD

**Issue by scopsy** [notifirehq/notifire#12]
### What?
Adds the ability to create theming configs (mainly for email and in-app). To create the basic look and feel layout for emails, element items.

### Why? 
Give developers the ability to easily switch themes for different customers and define them in a single place. Without specifying it with every message design. 

### How?
A new API will be provided for registering **Themes** and a default theme will be used for all messages unless specified otherwise. 

#### Template registration and definition
```typescript
const mainTheme = await notifire.registerTheme({
  id: 'main-theme',
  styling: {
      logo: "https://img.com/logo.png",
      
  },
  email: {
     layout: `
         <html>
             <head> </head>
             <body>
                  {{{body}}}
             </body>
         </html>
    `
  }
});
```

#### Usage
```typescript
notifire.trigger('event-name', {
 ...trigerContent,
  $theme: 'theme-id', // When using default no need to specify
  $branding: { // specified only when wanting to override theme settings
      logo: '',
      colors: {

      }
  }
})
```

### 3rd party themes
Allow the ability to create user-generated themes, each theme will give the ability to specify variables for used customizations.
```typescript
await notifire.registerTheme(
    new FunitoTheme({
       logo: '',
       headerImage: '',
       bannerColor: '',
       social: {
          facebook: ''
      }
   })
)
```

**Comment by ComBarnea** [comment]
Great idea,
I do have a couple of questions,
1. How would do expect one to use a theme while using a template?

Maybe register theme
```typescript
const mainTheme = await notifire.registerTheme({
  id: 'main-theme',
  styling: {
      logo: "https://img.com/logo.png",
      
  },
  email: {
     layout: `
         <html>
             <head> </head>
             <body>
                  {{{body}}}
             </body>
         </html>
    `
  }
});
```
after the theme is registered, add a template, using that theme

```typescript
const passwordResetTemplate = await notifire.registerTemplate({
  id: 'password-reset',
 $theme: 'theme-id', // <- This is New
  messages: [
    {
      subject: 'Your password reset request',
      channel: ChannelTypeEnum.EMAIL,
      template: `
          Hi {{firstName}}!
          
          To reset your password click <a href="{{resetLink}}">here.</a>
          
          {{#if organization}}
            <img src="organization.logo" />
          {{/if}}
      `
    },
  ]
});
```
This way one gains the ability to use, default, or not default theme. What do you think?

**Comment by scopsy** [comment]
> This way one gains the ability to use, default, or not default theme. What do you think?

Sounds good, I would use `template` instead of `$template` there. Using a `$` was mainly. to separate internal vs user variables when performing a `trigger`.
