### ISSUE TITLE
Add new SMS provider: Telnyx

### ISSUE THREAD

**Issue by samip5** [notifirehq/notifire#127]
**Is your feature request related to a problem? Please describe.**
No support for Telnyx SMS

**Describe the solution you'd like**
Support for it

**Additional context**
https://developers.telnyx.com/docs/v2/messaging

**Comment by Abobos** [comment]
@scopsy I would like to add support for the new provider Telnyx

**Comment by scopsy** [comment]
@Abobos Sure! You can read https://docs.notifire.co/docs/community/create-provider to get you started
