### ISSUE TITLE
Mailchimp provider

### ISSUE THREAD

**Issue by cloudguruab** [notifirehq/notifire#133]
**Is your feature request related to a problem? Please describe.**
I would like to work on adding MailChimp as a provider for Email based OCL

**Describe the solution you'd like**
This integration will support Email based communication between clients 

**Describe alternatives you've considered**
N/a -> the api is pretty straight forward 

**Additional context**

**Comment by cloudguruab** [comment]
I would like to be assigned to this issue and push this feature request @scopsy

**Comment by scopsy** [comment]
I'm not familiar with MailChimp transactional API, as far as I remember they use mandrill which we already have support.
Does Mailchimp offer an API for sending an email to a specific user as oppose to a list/campaign ?

**Comment by cloudguruab** [comment]
You can use Mailchimp Transactional for personalized, one-to-one e-commerce emails, as well as automated emails like password resets, order confirmations, and welcome messages. I see in their docs they are migrating mandrill into the transactional api they offer so I'll go ahead close this issue since implementing Mailchimp would be in ways pretty redundant!
