### ISSUE TITLE
HTML is not being rendered in `mailtrap` using `emailjs`

### ISSUE THREAD

**Issue by CharlieBrownCharacter** [notifirehq/notifire#151]
**Describe the bug**
HTML is not being rendered in Mailtrap when using `emailjs` provider

**Expected behavior**
HTML version of the email should be rendered in Mailtrap when using `emailjs` provider

**Additional context**
To fix this issue simply update your `package.json` with the newest version:

```
{
  "dependencies": {
    "@notifire/emailjs": "^0.3.5",
  }
}
```

**Comment by scopsy** [comment]
Thanks for the report! As you mentioned this was fixed at `@notifire/emailjs@0.3.5`
