### ISSUE TITLE
Allow `subject` to be passed a `function` and not only `string`

### ISSUE THREAD

**Issue by CharlieBrownCharacter** [notifirehq/notifire#152]
**Is your feature request related to a problem? Please describe.**
When sending notifications we need to localize the content of the message to the target user. Currently it is only allowed for `template` to be passed as a `function` [see here](https://github.com/notifirehq/notifire/blob/ed8f6b8d85035e85aa7075b6c22e6bd3d93a5772/packages/core/src/lib/handler/email.handler.ts#L37). It is useful to be able to localize the `subject` as well.

Unfortunately the `subject` only allows a `string` to be passed which will get evaluated when the template is registered. In cases of a webserver (such as express) this is not a viable solution because the string gets evaluated as soon as it is registered.

There are several projects using `i18n` as a singleton

```js
import i18n form 'i18n';

i18n.configure({
  directory: path.join(__dirname, '../translations'),
});
```

and the language is modified on the fly when an HTTP request is made to the application. Since the template was registered on application boot the `subject` cannot be re-evaluated, making us having to create several `messages`:

```js
await notifire.registerTemplate({
    id: "password-reset",
    messages: [
      {
        subject: "Your password reset request english",
        channel: ChannelTypeEnum.EMAIL,
        template: "",
        active: (payload) => {
          return payload.language === "en";
        },
      },
      {
        subject: "Your password reset request french",
        channel: ChannelTypeEnum.EMAIL,
        template: ",
        active: (payload) => {
          return payload.language === "fr";
        },
      },
    ],
  });
```

Which does not use `i18n` anywhere, but more like hardcoding the values. This brings a problem when the translations are managed by a different team. 

**Describe the solution you'd like**
A way to register the `subject` on demand respecting changes in a dynamic app. Something like:

```js
import { getTranslation } from './plugins/i18n'

  await notifire.registerTemplate({
    id: 'password-reset',
    messages: [
      {
        subject: () => getTranslation('translation-key'),
        channel: ChannelTypeEnum.EMAIL,
        template: "this is the awesome template",
      },
    ],
  });
```

We could even pass the configuration of the template in here as well to evaluate something other:

```js
subject: (template: ITemplate) => {
  if (template.someFutureConfiguration === 'foo') {
    return getTranslation('translation-key-foo')
  }
  
  return getTranslation('translation-key-bar');
},
```

**Describe alternatives you've considered**

**Additional context**
For the person that will work on this feature (mostly me) he can see examples of the same logic [here](https://github.com/notifirehq/notifire/blob/ed8f6b8d85035e85aa7075b6c22e6bd3d93a5772/packages/core/src/lib/handler/email.handler.ts#L37)

**Comment by scopsy** [comment]
We definitely can go with this implementation, I like the API for it. We later can facilitate a first-class citizen for translations, but this will solve it with some extra custom use-cases. 

One thing I think we can do is call the `compileTemplate` on the `template` key and on the `subject` key, for the sake of consistency.

If someone will want to bypass our handlebars engine for good, we can provide a config for that.

Assigned you on the task, so you can start working on that. I'll be glad to jump on board if you need any help with the implementation. 🤟

**Comment by CharlieBrownCharacter** [comment]
PR have been opened here for this issue https://github.com/notifirehq/notifire/pull/155
