### ISSUE TITLE
[Docs] - Provide an example of how to manage translation

### ISSUE THREAD

**Issue by scopsy** [notifirehq/notifire#154]
Following the conversation with @CharlieBrownCharacter about #152, we should add a recipe for our docs about how can people can integrate translations using the library.

**Comment by CharlieBrownCharacter** [comment]
Docs have been added in this PR as well https://github.com/notifirehq/notifire/pull/155 (specifically here https://github.com/notifirehq/notifire/pull/155/files#diff-f06b2aa4b0ed7f6742355afe6023ea21a1d4a6c583ab8df4a1fa58b981a9ea3cR1
