### ISSUE TITLE
[Tracking] NX workspaces support

### ISSUE THREAD

**Issue by scopsy** [notifirehq/notifire#164]
## Why?
Currently, the `lerna build` is quite slow locally and on GitHub actions during CI. Additionally, we can use nx to run diffs on changed services and other features.

## How?
Integrate using the nx [guide](https://nx.dev/l/r/migration/adding-to-monorepo)  for adding nx to an existing monorepo.
To set up the project for development run `npm run setup:dev` in the root directory for installing the project dependencies.

## Tasks
- [x] #165 
- [x] Test that nx build runs the `build` command successfully on all packages (apis, providers, libs, packages)
- [x] #166
- [x] #167
- [x] #171

**Comment by nishit-g** [comment]
Hey can I work on this @scopsy ?

**Comment by scopsy** [comment]
@nishit-g sure thing! Let me know if you need any help or stuck with some errors

**Comment by nishit-g** [comment]
Hey @scopsy , followed the steps and tried to run build all using nx.
Stuck here 

<img width="799" alt="Screenshot 2022-01-07 at 10 38 55 PM" src="https://user-images.githubusercontent.com/32142878/148580586-75df198b-fceb-4f23-9712-5496b945d19a.png">

But if I go ahead and remove the "config" option from package.json ( say from `packages/core/` ). the build command w/ nx works.

I am having trouble making nx exclude the "config" option from package.json as this exist in almost every lib/app.

Other solution I found was to create `.czrc` file and put the path config there. This results in successfull build w/ nx + keeps the needed functionality of commitizen.

**Comment by scopsy** [comment]
Let's go with your solution using the cz file. Amazing job finding the solution!

**Comment by nishit-g** [comment]
@scopsy  have made changes and nx builds 👇 these successfully. PR created just need to test the commitizen part.

<img width="799" alt="Screenshot 2022-01-08 at 10 05 42 AM" src="https://user-images.githubusercontent.com/32142878/148631529-0bf38aa4-8f2a-4167-b774-bb6113a580c4.png">

<img width="799" alt="Screenshot 2022-01-08 at 10 06 56 AM" src="https://user-images.githubusercontent.com/32142878/148631555-e13e33a3-c061-427f-98a1-213710a097a5.png">

**Comment by scopsy** [comment]
@nishit-g Looks very good, I will check out the nx cloud option, if it can help with distributed caching and improve build times on CI I'm in for it. 

About the update of the `generate:provider` I'll create a dedicated issue for that.

Thank you so much for this one, super excited for this and it will help reduce the build time for all of our contributors 🥰

**Comment by scopsy** [comment]
@nishit-g Created the new issues and attached them here for tracking. I'll handle the package.json scripts :)

**Comment by nishit-g** [comment]
Done! you can check PR #168
