### ISSUE TITLE
Update generate:provider to use `.czrc` file instead of `package.json`

### ISSUE THREAD

**Issue by scopsy** [notifirehq/notifire#166]
## Why?
When migrated to NX at #165 there was an error mentioned by @nishit-g from the commitizen action with NX. So we decided to move the commitizen config from `package.json` to a dedicated `.czrc` file.

**Comment by nishit-g** [comment]
Hey @scopsy, I think I understand the flow for this script. Can you assign me this ?

**Comment by scopsy** [comment]
Sure! Btw, are you on our Discord channel?

**Comment by nishit-g** [comment]
No @scopsy, joining it right away though, want to contribute more! 💯
