### ISSUE TITLE
[RLD-45] - Border style on window widget #176

### ISSUE THREAD

**Issue by MatanMaimon** [notifirehq/notifire#176]
**Describe the bug**\
The window of the widget ([https://widget.notifire.co/K6TeacX0ig6Y](https://widget.notifire.co/K6TeacX0ig6Y)) displays an annoying border that corrupts the border radius.

**Screenshots**

[https://user-images.githubusercontent.com/6213171/149118496-2b65ce21-4c2a-476d-bcea-410fda5c3452.png](https://user-images.githubusercontent.com/6213171/149118496-2b65ce21-4c2a-476d-bcea-410fda5c3452.png)

**Details (please complete the following information):**

* OS: any
* Node Version: any

**Additional context**\
I noticed the simple fix it's to change to `border: 0` as in the screenshot (attached) but since the iframe CORS policy we can't do anything about it.

[https://user-images.githubusercontent.com/6213171/149119278-9b5e0c81-a12c-4523-9b01-c89d3963477b.png](https://user-images.githubusercontent.com/6213171/149119278-9b5e0c81-a12c-4523-9b01-c89d3963477b.png)

**Comment by scopsy** [comment]
Thanks for reporting @MatanMaimon are you experiencing this also when embedding the notification using the iframe embed script aswell? This border only exist in the dev mode when visiting the link you mentioned directly and not via the iframe.

**Comment by MatanMaimon** [comment]
> Thanks for reporting @MatanMaimon ! are you experiencing this also when embedding the notification using the iframe embed script aswell? This border only exist in the dev mode when visiting the link you mentioned directly and not via the iframe.

Yes we do use the iframe (code below).
*Please note to my edit 
![image](https://user-images.githubusercontent.com/6213171/149119840-ad7e67d4-6f81-4397-b34c-feb735057805.png)

**Comment by scopsy** [comment]
@MatanMaimon got ya. Taking a look.

**Comment by MatanMaimon** [comment]
> @MatanMaimon got ya. Taking a look.

did you notice the problem? is there a fix expected?

**Comment by scopsy** [comment]
@MatanMaimon we see it, I believe a fix will be shipped during this week. I'll update here once it's live 🎊.

**Comment by djabarovgeorge** [comment]
Hey, @MatanMaimon we just released a fix. Please let us know if you're still noticing any issues.
