### ISSUE TITLE
[RLD-53] - Deploy images to DockerHub

### ISSUE THREAD

**Issue by scopsy** [notifirehq/notifire#183]
## Why?

Instead of building the image every time when doing docker-compose up we want to prebuilt the images so users can easily consume them without the need to rebuild everything from the stretch. 

## How?

Add build scripts for the relevant services in the root `package.json` in the following structure `build:docker:api` and etc. for each service in `docker-compose.yml` respectively.

The images should be deployed to our organizational user hosted on the `relayed` user on DockerHub.

**Comment by samip5** [comment]
I would recommend to deploy to Github Container Registry too.

**Comment by scopsy** [comment]
Hi @samip5 thanks for the suggestion. I'm actually not very familiar with the GitHub container registry. Does it offer benefits over DockerHub? One thing I'm I'm concerned is how easy is to use the images.
With the docker hub repo it's just running `notifirehq/notifire`, for the GitHub repository a user needs to log in somewhere to access the public images?

**Comment by samip5** [comment]
> Hi @samip5 thanks for the suggestion. I'm actually not very familiar with the GitHub container registry. Does it offer benefits over DockerHub? One thing I'm I'm concerned is how easy is to use the images.
> With the docker hub repo it's just running `notifirehq/notifire`, for the GitHub repository a user needs to log in somewhere to access the public images?

You can only push images to the Github Docker regiatry from Github Actions and they don't have an annoying ratelimit for pulling unlike DockerHub has. 

Usee doesn't need to log-in,  it's pretty much the same as DockerHub but without ratelimits for pulling. 

So you could have a `ghcr.io/notifirehq/notifire`.

**Comment by djabarovgeorge** [comment]
Closing this issue due to the first push to the Github Container Registry.
Thanks, @samip5 for pointing us forward the pros regarding GHCR 🤟
