### ISSUE TITLE
💭 Idea: feed.context.ts should return empty object instead of null

### ISSUE THREAD

**Issue by wh1337** [notifirehq/notifire#2094]
### 🔖 Feature description

As it currently stands, `feed.context.ts` located [here](https://github.com/novuhq/novu/blob/2d3050a13b5dfc77b0d66e34ed2eac8a25299631/packages/notification-center/src/store/feed.context.ts#L10) is returning a null value by default. 

This can throw a `TypeError: Cannot read properties of null (reading 'activeTabStoreId')` on the Notifications Center if it's not yet unitized. After speaking with David and Pablo, it was thought that a change to an empty array would serve better.

### 🎤 Why is this feature needed ?

Potentially better error handling. 

### ✌️ How do you aim to achieve this?

Change the `null` value for `{}`

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by scopsy** [comment]
Sounds like a plan @cryptic-ai! Thanks for raising this

**Comment by jainpawan21** [comment]
Hi @cryptic-ai, Yes you can create PR.
Let us know in discord if you need any help

**Comment by richardeinhorn** [comment]
Hi @whodges2, any updates on this issue?
