### ISSUE TITLE
Add Attachments Support

### ISSUE THREAD

**Issue by ComBarnea** [notifirehq/notifire#21]
### What?
Adds the ability to send attachments with email providers ```ts IEmailOptions```.

### Why? 
Give developers the ability to add attachments to email providers, later on for push, direct, and in-app. 

### How?
Update email options interface, and later on update providers.

#### New Attachments Interface
```typescript
interface IAttachmentOptions {
    attachmentType: 'url' | 'buffer';
    mime: string;
    path?: string;
    file?: Buffer;
    name?: string;
}
```

#### Usage
```typescript
interface IEmailOptions {
    to: string | string[];
    subject: string;
    html: string;
    from?: string;
    attachments: IAttachmentOptions[];
}
```

## Tasks
- [x] #103
- [x] #104
- [x] #95
- [x] #96

## Provider support
- [x] #94
- [x] #97
- [x] #98
- [x] #99
- [x] #100
- [x] #101
- [x] #102

**Comment by davidsoderberg** [comment]
Maybe I could help with this?

**Comment by scopsy** [comment]
@davidsoderberg Sure! One thing that is missing is the `$attachment` attribute on the `ITriggerPayload` interface. So when triggering an event the attachment will pass to the appropriate provider.

Another thing I've been thinking on is the ability to control the attachments per message. For example, you want to add attachments on email but not on SMS. What do you think is the best approach to solving this?

**Comment by scopsy** [comment]
Also, I think it's best to just allow a buffer for now instead of a URL path, since managing and downloading external assets is quite dangerous from our end and is better to be controlled by the user. 

So instead of a `path` attribute I would use: `data` and it will be of Buffer type.  wdyt? @ComBarnea @davidsoderberg

**Comment by davidsoderberg** [comment]
> Another thing I've been thinking on is the ability to control the attachments per message. For example, you want to add attachments on email but not on SMS. What do you think is the best approach to solving this?
Do you mean that SMS should not handle attatchments or did I understand you wrong?

**Comment by davidsoderberg** [comment]
> So instead of a `path` attribute I would use: `data` and it will be of Buffer type. wdyt?

I agree can be very dangerous to handle it in this package 😄

**Comment by davidsoderberg** [comment]
```
export interface ITriggerPayload {
  $email?: string;
  $phone?: string;
  $user_id: string;
  $theme_id?: string;
  attachments: IAttachmentOptions[];
  [key: string]:
    | string
    | boolean
    | number
    | undefined
    | IAttachmentOptions
    | IAttachmentOptions[];
}

export interface IAttachmentOptions {
  mime: string;
  file: Buffer;
  name?: string;
}
```

What do you guys think?

**Comment by scopsy** [comment]
Sounds good to me! @davidsoderberg  Just make the attachments optional.

About the SMS part, For example, I want to send attachments to email and not to slack or SMS. Or in other cases, I want to send them to all of the channels. I think we should provide an option to manage the sending of attachments.

**Comment by davidsoderberg** [comment]
Adding ChannelTypeEnum to IAttachmentOptions and then we can filter them out in each handler?

**Comment by scopsy** [comment]
@davidsoderberg Good idea we can add an array of them. And if no array was provided all the providers that support attachments will send them.

**Comment by davidsoderberg** [comment]
```
export interface IAttachmentOptions {
  mime: string;
  file: Buffer;
  name?: string;
  channel?: ChannelTypeEnum[];
}
```

Like this?

**Comment by scopsy** [comment]
I think `channels` would be great in plural

**Comment by davidsoderberg** [comment]
Yeah agree I thought first it would be a single one but totally understand why it should be an array 😄

**Comment by scopsy** [comment]
@davidsoderberg Looks like we are done with all of them 🎉🚀
