### ISSUE TITLE
[NV-185] - Add variable protection docs

### ISSUE THREAD

**Issue by ComBarnea** [notifirehq/notifire#22]
### **What?**

Missing documentation for variable protection

### **How?**

Add missing doc, under templates in docs.\
[https://user-images.githubusercontent.com/8877285/134776747-1ecfe72f-c8a2-48c2-81d2-79c926804bc8.png](https://user-images.githubusercontent.com/8877285/134776747-1ecfe72f-c8a2-48c2-81d2-79c926804bc8.png)

### **Where?**

Code can be found in TriggerEngine class

**Comment by ninjadev101** [comment]
@scopsy I can work on this.

**Comment by ninjadev101** [comment]
[Draft Link](https://docs-git-fork-ninjadev101-nv-185-variable-protect-a4f6ba-novuhq.vercel.app/docs/templates/variable_protection)

**Comment by ninjadev101** [comment]
https://github.com/notifirehq/notifire/pull/351
