### ISSUE TITLE
 Add hooks docs

### ISSUE THREAD

**Issue by ComBarnea** [notifirehq/notifire#23]
### What?
Missing documentation for hooks

### How?
Add missing doc, under templates in docs.
![Templates location](https://user-images.githubusercontent.com/8877285/134776747-1ecfe72f-c8a2-48c2-81d2-79c926804bc8.png)

### Where?
Code can be found in TriggerEngine class

**Comment by rrhythmsharma** [comment]
Hi @ComBarnea 

Should I pick this up?

**Comment by scopsy** [comment]
Sure @rrhythmsharma ! I'll assign you, feel free to reach out if you need any help or clarification :)

**Comment by rrhythmsharma** [comment]
@ComBarnea @scopsy 

Please review the PR
