### ISSUE TITLE
[NV-1516] Novu/web container is getting exited due to some error

### ISSUE THREAD

**Issue by Niba-nazar** [notifirehq/notifire#2423]
Hi, 

I am trying to set up novu using docker container and am getting the below error:
![image](https://user-images.githubusercontent.com/114569256/210567002-0b72f053-a2cb-42ec-a753-2b4ed972dc6e.png)

Tried to get the image from web:latest and succeeded in creating the container. However, the url: http://localhost:4200 cannot be used to access the web interface 
Could you please help me to resolve the issue

<sub>[NV-1516](https://linear.app/novu/issue/NV-1516/novuweb-container-is-getting-exited-due-to-some-error)</sub>

**Comment by MichalNemec** [comment]
hello its fixed in [4d6e24452] wipe everything and it should be okay, got the error today too.

**Comment by Niba-nazar** [comment]
Hi, 


Why api container is showing logs like this:
![image](https://user-images.githubusercontent.com/114569256/210738421-7a73900c-e33e-4a81-9979-bd119a1f500e.png)



Also while running "docker-compose -f ./local/deployment/docker-compose.yml up" these many warning are coming:
![image](https://user-images.githubusercontent.com/114569256/210738969-34c8abfa-8127-4ba9-9f13-1840c282f09c.png)

**Comment by MichalNemec** [comment]
are you sure you wiped everything? i think i got this one time and it seems like its mising .env 
When i do cleanup:
- wipe container
- wipe images
- wipe volumes

- git clone novu
- copy .env
- compose (just like on the docs)

**Comment by Niba-nazar** [comment]
Yes, this time I tried on a different server,

**Comment by scopsy** [comment]
@Niba-nazar will close this issues since the original error was fixed. If you still encounter the missing variables feel free to send a message on Discord so we can help there 🙏
