### ISSUE TITLE
[RLD-105] - Create a local server on ephemeral port

### ISSUE THREAD

**Issue by djabarovgeorge** [notifirehq/notifire#256]
## Why?
For the API usage after the authentication, the API can replay to the CLI with the GitHub OAth payload.

## How?
The CLI will raise a native HTTP server because it is the 

http-server was chosen because is is light wight and we do not need any complex functionality/features.

### Ref:
https://javascript.plainenglish.io/fastify-express-benchmark-4c4aebb726d6

**Comment by rannn505** [comment]
Hey, @djabarovgeorge here's an optimization suggestion: use [get-port](https://github.com/sindresorhus/get-port) to find a free TCP port.

**Comment by djabarovgeorge** [comment]
Hey @rannn505, currently I am using a pre-drawn port number but your solution seems much more durable, I will consider adding it.
Thank you for raising it up! 💪

**Comment by djabarovgeorge** [comment]
Closed by #257
