### ISSUE TITLE
[NV-1559] 🐛 Bug Report: Trouble with apostrophe’s sending SMS with Twilio

### ISSUE THREAD

**Issue by cmaycumber** [notifirehq/notifire#2564]
### 📜 Description

We’re trying to send a broadcast to all our subscribers which includes an apostrphe in the text.

This is seemingly converted into unicode characters somewhere along the line and prior, to using Novu we just used Twilio directly and things seemed to send fine through there API. 

Could Novu be replacing the apostrophe with a unicode character causing our messages to come across funny to users? 

### 👟 Reproduction steps

1. Create a broadcast with the Novu API with a message body containg a apostrophe

### 👍 Expected behavior

Not convert the apostrohpe to unicode and send that unicode in the SMS

### 👎 Actual Behavior with Screenshots

![IMG_6BB2F50E9A47-1](https://user-images.githubusercontent.com/36460656/213759870-cfde6b6b-29f9-428f-b098-6786486af761.jpeg)

### 🤖 Node Version

18

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1559](https://linear.app/novu/issue/NV-1559/🐛-bug-report-trouble-with-apostrophes-sending-sms-with-twilio)</sub>

**Comment by ainouzgali** [comment]
Also push.

**Comment by scopsy** [comment]
This should be possible now using Echo: https://docs.novu.co/echo/quickstart
