### ISSUE TITLE
Add new Nexmo provider

### ISSUE THREAD

**Issue by ComBarnea** [notifirehq/notifire#26]
### What?
New [Nexmo](https://github.com/Vonage/vonage-node-sdk) SMS Provider

### Why?
To have the ability to use [Nexmo](https://github.com/Vonage/vonage-node-sdk)  as a provider.

### How?
Add new provider based on [this guide](https://docs.notifire.co/docs/community/create-provider)

### Usage
Example for Nexmo provider registration needs to be finalized.

```ts
await notifire.registerProvider(
  new NexmoProvider({
    apiKey: process.env.NEXMO_API_KEY
  })
);
```

**Comment by scopsy** [comment]
@painotpi Sure, assigned you. Let me know if you need any help 🙌

**Comment by scopsy** [comment]
Sorry, @painotpi missed your message here about looking for help :( Looks like Nexmo was already added by someone at https://github.com/notifirehq/notifire/pull/136

Went over your fork, I believe there is some issue with jest mock there. Thank you so much for your contribution regardless, I really appreciate it.
