### ISSUE TITLE
npm run setup:project failed

### ISSUE THREAD

**Issue by abrl91** [notifirehq/notifire#271]
**Describe the bug**
npm run setup:project failed

**To Reproduce**
1. git clone https://github.com/abrl91/notifire.git
2. cd notifire
3. npm run setup:project
4. See errors on init.ts and http-server.ts
```
Cannot find name 'REDIRECT_ROUTH'.
src/server/http-server.ts(2,36): error TS2724: '"../constants"' has no exported member named 'REDIRECT_ROUTH'. Did you mean 'REDIRECT_ROUTE'?
```

**Expected behavior**
![image](https://user-images.githubusercontent.com/39680385/154521720-18894cb1-31f7-45ce-9f8d-864ea06d42d6.png)

**Details (please complete the following information):**
 - OS: macOS
 - Node Version 14.17.3

**Comment by scopsy** [comment]
Thanks for the report! 
Looks like `REDIRECT_ROUTE` was translated to pirate language 🤣

@djabarovgeorge I think it's related to #269, could you take a look?

**Comment by djabarovgeorge** [comment]
Sure think!  looks like pirates to me 😅
