### ISSUE TITLE
[NV-1902] 🚀 Feature: Automatically delete old messages

### ISSUE THREAD

**Issue by ryshoooo** [notifirehq/notifire#3071]
### 🔖 Feature description

Would it be possible to configure a TTL on sent messages? Such that the sent messages would be automatically deleted after, f.e. 6 months. I'm not sure if this already exists, I couldn't find anything. It is mainly not to waste storage with data that's just useless.

### 🎤 Why is this feature needed ?

Save up on storage costs for MongoDB

### ✌️ How do you aim to achieve this?

I'd suggest adding a TTL value for a notification configurable from the template or upon trigger. When the TTL is reached, some process would automatically delete the message.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1902](https://linear.app/novu/issue/NV-1902/🚀-feature-automatically-delete-old-messages)</sub>

**Comment by oba2311** [comment]
AFAIK we are in the process of implpementing those. Don't see why in the near future we would make those configurable. @Cliftonz  can tell more.

**Comment by Cliftonz** [comment]
@ryshoooo Yes, @ainouzgali and I are planning to begin working adding TTL next week. 
This should be something very simple to add as we are working on this piece of the system.
