### ISSUE TITLE
Add new mandrill provider

### ISSUE THREAD

**Issue by ComBarnea** [notifirehq/notifire#38]
### What?
New [Mandrill](https://github.com/mailchimp/mailchimp-transactional-node) Email Provider

### Why?
To have the ability to use [Mandrill](https://github.com/mailchimp/mailchimp-transactional-node)  as a provider.

### How?
Add new provider based on [this guide](https://docs.notifire.co/docs/community/create-provider)

### Usage
Example for Mandrill provider registration needs to be finalized.

```ts
await notifire.registerProvider(
  new MandrillProvider({
    apiKey: process.env.MANDRILL_API_KEY
  })
);
```

**Comment by diganta413** [comment]
Can I work in these issue?

**Comment by scopsy** [comment]
@diganta413 No problem, you can create a `Draft` pr of the progress to advise if you are stuck. And you can also join our discord server: https://discord.gg/zuJBrUbfgs
