### ISSUE TITLE
Upgrade to 0.16.3 (0.16.4)

### ISSUE THREAD

**Issue by katyaterletskaya** [notifirehq/notifire#3820]
### Discussed in https://github.com/novuhq/novu/discussions/3788

<div type='discussions-op-text'>

<sup>Originally posted by **katyaterletskaya** July 13, 2023</sup>
Hi 😊 Could you add `0.16.3` tag to images in the GitHub registry? </div>

I decided to create an issue from the discussion without an answer. Thanks in advance for the help 🙂

**Comment by jlucidar** [comment]
it seems that docker image are not yet tagged automatically when a new release is done. If you want 0.16.3 you can use tag `prod` or directly the commit sha `2dbd3f66cb9b6e4a1a7fbd5b33cd6ccc85465482`

There is a github action that needs to be triggered manually to tag the images : https://github.com/novuhq/novu/actions/workflows/tag-images.yml

@scopsy any specific reason not to automate this ?

**Comment by katyaterletskaya** [comment]
@scopsy could you trigger a workflow to tag images? 😊

**Comment by scopsy** [comment]
@jlucidar No specific reason, unfortunately just didn't had a chance to automate it yet :) @katyaterletskaya will be tagging a version later today 🙏

**Comment by scopsy** [comment]
@katyaterletskaya tagged 0.16.4 (you can pull it) will be publishing 0.17.0 soon aswell

**Comment by scopsy** [comment]
Hi @katyaterletskaya not yet, we are finishing the release notes today/tomorrow and hope we will be able to tag an image in the weekend/beginning of next week.

**Comment by katyaterletskaya** [comment]
@scopsy thank you for the quick reply!

**Comment by scopsy** [comment]
@katyaterletskaya tagged 0.17.1 🎉
