### ISSUE TITLE
🐛 Bug Report: digest not bucketing events with same digestKey

### ISSUE THREAD

**Issue by joaonlforte** [notifirehq/notifire#3893]
### 📜 Description

Hey Novu team 👋 ,

I'm leveraging notifications for a workflow in a data acquisition pipeline. The data flow is highly concurrent and event driven.

I configured the digest step as shown (attached img. I'm triggering the notifications and I want to aggregate events that share the same key (e.g. an ULID `id` of domain entity that acts as an aggregator entity on my system), in order to send a single summary email per subscriber (user) of a given topic 

<img width="1035" alt="image" src="https://github.com/novuhq/novu/assets/5887317/74975325-8acb-4aed-be1d-eae4915991cd">

### 👟 Reproduction steps

Trigger events with a digest key and without guarantee of order

### 👍 Expected behavior

Accordingly to the [documentation](https://docs.novu.co/platform/digest/#digest-key) the events would be aggregated as `subscriberId` + `key`

Taking as data source:

| subscriberId | key |
|--------|--------|
| 123 | abc | 
| 123 | def | 
| 123 | abc |
| 123 | def | 

would end up in sending 2 emails to subscriber `123`, with the following events aggregations

email 1
| subscriberId | key | 
|--------|--------|
| 123 | abc |
| 123 | abc |

email 2
| subscriberId | key |
|--------|--------|
| 123 | def |
| 123 | def |

### 👎 Actual Behavior with Screenshots

It seems it's not respecting the aggregation key, subscriber is receiving an email for events with different keys

| key |
|--------|
| abc | 
| def | 
| abc |
| def | 

below i'm attaching a SS with the events coming in `step.events` array and being rendered by the digest template

<img width="297" alt="image" src="https://github.com/novuhq/novu/assets/5887317/9a70b64d-17e3-44eb-9741-1e95acc466fd">

I was expecting all the events coming in the `step.events` array to share the same key

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by ainouzgali** [comment]
Hi @joaonlforte :) what novu version are you using? Or are you using our cloud version?

**Comment by ainouzgali** [comment]
Hi @joaonlforte I was not able to reproduce, it is working as expected for me. Could you please look at the activity feed and tell me what you see there? Also inside the 'Digest triggered events'. And the trigger snippet you are using :)
<img width="1508" alt="Screen Shot 2023-08-02 at 12 56 34" src="https://github.com/novuhq/novu/assets/7778680/5781440d-ed7d-4d77-a8e2-129c9314d79d">

**Comment by scopsy** [comment]
@joaonlforte a fix was deployed for this issue to our cloud service, let me know if you have experienced this again after it was deployed 🙏
