### ISSUE TITLE
Template Schema Validation 

### ISSUE THREAD

**Issue by ComBarnea** [notifirehq/notifire#4]
- **I'm submitting a ...**
  [ ] bug report
  [X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Add for variable schema for templates
- [ ] Add option for variable validation using Joi, Yup, class-validator, and such
- [ ] Add option for a variable to fall back if missing of failing validation

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by davidsoderberg** [comment]
@scopsy do you guys mind if I dig my head into this issue?

**Comment by ComBarnea** [comment]
@davidsoderberg sure thing, assigning this to you right now, @scopsy do you have anything else to add here?

**Comment by scopsy** [comment]
@davidsoderberg sure! You can outline and API for the validations so we can discuss it with the community? 

Some initial thoughts: we can create an API that will allow any validation system to work using some sort of plugin approach. This can support validators like Joi or class validators. Or just a simple function validation with custom logic.

**Comment by davidsoderberg** [comment]
I was thinking of a function that can be a promise and then we do not catch it so the error can be catched by the user of the package. Any thoughts on that?

**Comment by scopsy** [comment]
This can be the validator schema, the main thing is that each validator should return a validate function, the implementation doesn't matter as long as the validate method exists.
```typescript
interface ITemplateSchema {
   validate(payload: ITriggerPayload): Promise<boolean>;
}
```
This is one implementation for JOI, we can use similar once to validate with other validator libraries or custom code.
```typescript
class JoiValidator implements ITemplateSchema {
    constructor(private schema: JoiSchema) {

    }

    async validate(payload: ITrigger) {
      await this.schema.validateAsync(payload);
      return true;
   }
}
```

Not sure about the `schema` key here maybe we can find a better name? 
And I think this should be on the template level or the message level?
```typescript
const passwordResetTemplate = await notifire.registerTemplate({
  id: 'password-reset',
  schema: new JoiValidator(Joi.object({
    username: Joi.string()
        .alphanum()
        .min(3)
        .max(30)
        .required()
   })),
  messages: [
    {
      subject: 'Your password reset request',
      channel: ChannelTypeEnum.EMAIL,
      template: `
          Hi {{firstName}}!
      `
    },
  ]
});
```
