### ISSUE TITLE
Add new emailjs provider

### ISSUE THREAD

**Issue by ComBarnea** [notifirehq/notifire#40]
### What?
New [emailjs](https://github.com/eleith/emailjs) Email Provider

### Why?
To have the ability to use [emailjs](https://github.com/eleith/emailjs)  as a provider.

### How?
Add new provider based on [this guide](https://docs.notifire.co/docs/community/create-provider)

### Usage
Example for emailjs provider registration needs to be finalized.

```ts
await notifire.registerProvider(
  new EmailJsProvider({
    from: "support@supercorp.io",
    host: "smtp.test.email",
    port: 587,
    secure: false, // true for 465, false for other ports
    user: "userName", // generated ethereal user
    password: "password",
  })
);
```

**Comment by artfuldev** [comment]
Hi!

From https://docs.notifire.co/docs/community/create-provider, I see that we have an `IEmailProvider` interface, and we need an implementation of that interface for https://github.com/eleith/emailjs

I suppose the registration would look something like:
```ts
await notifire.registerProvider(
  new EmailJsEmailProvider(config)
);
```

Is that correct?
