### ISSUE TITLE
[NV-2971] [NV-2842] Add Trigger Identifier to the Subscriber Preferences response

### ISSUE THREAD

**Issue by jainpawan21** [notifirehq/notifire#4417]
### What?

Add the `triggers` field to be part of the response to the query. The mapping functionality is included in this file: [https://github.com/novuhq/novu/blob/58c46d72367f0f71bb0dd6b2014c2d5c6a8adcc3/packages/application-generic/src/usecases/get-subscriber-template-preference/get-subscriber-template-preference.usecase.ts#L252](https://github.com/novuhq/novu/blob/58c46d72367f0f71bb0dd6b2014c2d5c6a8adcc3/packages/application-generic/src/usecases/get-subscriber-template-preference/get-subscriber-template-preference.usecase.ts#L252)

### Why?

Some users would love to filter the preferences based on the identifier of the trigger.

### Definition of Done

* `GET /:subscriberId/preferences/:templateId` response contains the triggers array in the `template` field.
* A new E2E test at `apps/api/src/app/subscribers/e2e/get-preferences.e2e.ts` to cover the functionality

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-2842](https://linear.app/novu/issue/NV-2842/add-trigger-identifier-to-the-subscriber-preferences-response)</sub>

<sub>[NV-2971](https://linear.app/novu/issue/NV-2971/[nv-2842]-add-trigger-identifier-to-the-subscriber-preferences)</sub>

**Comment by suryanshsoni120** [comment]
I would like to work on this. Can you assign it to me?

**Comment by Ashish2271** [comment]
I would like to work on this issue. Can you please assign this issue to me?

**Comment by manish7017** [comment]
Could you please assign this issue to me? I would like to work on it

**Comment by davidsoderberg** [comment]
@suryanshsoni120 I will assign you now

**Comment by Itsamanjain** [comment]
@davidsoderberg , when I am running the web project on my localhost at port 4200, a login page appears, prompting for login either through GitHub or by using an email. I have tried both options but cannot successfully log in. Is there a **default username and password** for logging in during the localhost development phase?

**Comment by davidsoderberg** [comment]
No you need to sign up to be able to login, please use discord for further questions :)

**Comment by vichustephen** [comment]
I would like to take this up. Please assign it to me

**Comment by nick2432** [comment]
can i work on this issue?

**Comment by Chandan-Singh10** [comment]
I am willing to work on this issue please assign me this issue

**Comment by scopsy** [comment]
Hi @suryanshsoni120 any updates on your end? Let me know if I should assign someone else on this

**Comment by ayushshukla7777** [comment]
hey @jainpawan21 , I was attemping to solve this issue and found that trigger is of type NotificationTriggerEntity which is in @novu/dal.
While the Interface where I need to add trigger is in @novu/shared. 
Importing @novu/dal in @novu/shared causes dependency circle.
![image](https://github.com/novuhq/novu/assets/53791140/c8191ad9-9fd6-4cec-b97d-d65830ce309e)

**Comment by suryanshsoni120** [comment]
I was actually facing difficulties in setup. It's resolved and am working on the issue.

**Comment by djabarovgeorge** [comment]
Due to the urgency of this issue and the lack of a current solution, I've taken the initiative to raise a PR to resolve it.

Thank you for your understanding.
