### ISSUE TITLE
🐛 Bug Report: cannot trigger workflow with topic

### ISSUE THREAD

**Issue by lukmanfarizi** [notifirehq/notifire#5571]
### 📜 Description

With Novu v.0.24, I am unable to trigger workflows with topics, whereas it worked in v.0.22. Although the API results indicate success with a ‘processed’ status, the trigger is neither being called nor recorded in the activity feed.

### 👟 Reproduction steps

parameter to trigger topic,

`{
    "name": "event-started",
    "to": {
        "type": "Topic",
        "topicKey": "notification"
    },
    "payload": {
        "alert": "xxxxx"
    }
}`

result from novu,
`{
    "data": {
        "acknowledged": true,
        "status": "processed",
        "transactionId": "24a5b418-f789-417c-ab81-ed951f93df0a"
    }
}`

### 👍 Expected behavior

it should trigger workflow

### 👎 Actual Behavior with Screenshots

![image](https://github.com/novuhq/novu/assets/2754458/b5986b17-819b-4750-a187-2907e3b0fc05)

### Novu version

V.0.24.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by ainouzgali** [comment]
Hi @lukmanfarizi :) 
Could you please try having to as an array of objects. Like this:
`{ "name": "event-started", "to": [{ "type": "Topic", "topicKey": "notification" }], "payload": { "alert": "xxxxx" } }`

**Comment by ainouzgali** [comment]
@lukmanfarizi did you get a chance to try what I suggested? It should work, please let me know if you still have problems with that. 
Assuming it did work for you - I will open a ticket for having a correct validation error for this.

**Comment by lukmanfarizi** [comment]
@ainouzgali, I apologize for the delayed response.

 I have already tested your suggestion, but unfortunately, it is still not working. I attached capture from postman.
 
 
![image](https://github.com/novuhq/novu/assets/2754458/1d5c5fd8-99a7-49c1-83f9-9093b332ad74)

**Comment by mohamed-cherifi** [comment]
Hello, 

I am having a similar issue. 
I am using Novu 0.23
Here's what I've tried so far with no luck:

- Direct API trigger
<img width="1234" alt="image" src="https://github.com/novuhq/novu/assets/97466700/ccfadd7e-a34a-43af-abea-9f735ceb6e1f">

- Node novu trigger sdk
<img width="713" alt="image" src="https://github.com/novuhq/novu/assets/97466700/0f8dd761-e186-4652-9f14-cadf33cac46a">

- Node novu.events trigger sdk
<img width="667" alt="image" src="https://github.com/novuhq/novu/assets/97466700/99604e5b-2d09-4a71-8145-7d627f8cd623">

So even when I tried to trigger the topic via a direct api call the notification didn't appear on the activity feed.
But if I trigger the notification the standard way, ie with a subscriber id it does work as expected.

For additional context here's the list of topics:
<img width="550" alt="image" src="https://github.com/novuhq/novu/assets/97466700/2440a57c-baa3-46b0-9082-b3626fd449a7">

**Comment by BlackH3art** [comment]
Hello,

@lukmanfarizi @mohamed-cherifi 

The question is what version of Novu are you using? Is it the claud version or the selfhosted version? 

I had exactly the same issue using self-hosted version. Topics were processed and properly sent but no actual notification was delivered. 
After couple days and discussion on Discord, it turns out that there is **environment variable** called `IS_TOPIC_NOTIFICATION_ENABLED` required in order for topic to be actually send.

If you're using self-hosted version, then adding this line in `/docker/local/deployment/docker-compose.yml` under the `worker` service in `environment` section should solve the problem:
```
IS_TOPIC_NOTIFICATION_ENABLED: true
```

Or in `.env` files if you run Novu locally, not using `docker-compose`.

**Comment by ngonam22** [comment]
Hello @BlackH3art and thank you for your solution!!

Im using the latest version of Novu self hosted and have the exact same problem.  Took me hours to digging around the source code but found nothing!! 
Anw really wonder what happened? We missed this Flag in our document or something?
