### ISSUE TITLE
Update calendly link to Hubspot meeting

### ISSUE THREAD

**Issue by justnems** [notifirehq/notifire#5632]
https://github.com/novuhq/novu/blob/dbbcdc7ceca62f79f71cda4d12888bf0fab437d4/apps/web/src/components/utils/ProductLead.tsx#L107

Current Calendly link in app needs to be pointed to Hubspot meeting request instead.

New link: https://notify.novu.co/meetings/novuhq/notifications-45min?utm_campaign=in-app

**Comment by SokratisVidros** [comment]
[Fixed](https://github.com/novuhq/novu/commit/119baea19e60c0a8e849de3d0203aa6a02eaa188)
