### ISSUE TITLE
🚀 Feature: SvelteKit Serve Function Addition

### ISSUE THREAD

**Issue by awbx** [notifirehq/notifire#5649]
### 🔖 Feature description

The feature involves adding a SvelteKit serve function 

### 🎤 Why is this feature needed ?

This feature is needed because SvelteKit users, like myself, lack a standardized serve function. To address this gap in the community, I've taken the initiative to develop one for the benefit of fellow developers

### ✌️ How do you aim to achieve this?

I aim to achieve this by simply following the documentation provided.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by rifont** [comment]
Thanks for reporting this @awbx !

We have shipped native support for Sveltekit in [@novu/echo@0.24.3-alpha.1](https://www.npmjs.com/package/@novu/echo/v/0.24.3-alpha.1) 🎉

[Usage docs for Sveltekit serve function](https://docs.novu.co/echo/sdk/frameworks/sveltekit) are also available today.
