### ISSUE TITLE
🐛 Bug Report: Icon layoutShift when scrolling

### ISSUE THREAD

**Issue by somkumar-CT** [notifirehq/notifire#5660]
### 📜 Description

On /auth/application page icon and corresponding text doesn't stick together when scrolling 

### 👟 Reproduction steps

after logging in you get treated with /auth/application page and you can try scrolling.

### 👍 Expected behavior

There should be a scroll effect in the first place, at the very least both icon and corresponding text should stick with each other

### 👎 Actual Behavior with Screenshots

https://github.com/novuhq/novu/assets/161596375/666e6815-0d27-4936-8894-6342ffd0d170

### Novu version

Novu SaaS

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by harshit078** [comment]
@somkumar-CT Can I take this up ?

**Comment by somkumar-CT** [comment]
@harshit078 just do it and submit a pr you don't need to wait till someone assigns you.

**Comment by antonjoel82** [comment]
Thank you for creating this ticket! Marking this issue as resolved because we removed the problematic icons in [this PR](https://github.com/novuhq/novu/pull/5991)
