### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by hjh1cb** [notifirehq/notifire#5791]
### 📜 Description

![image](https://github.com/novuhq/novu/assets/83523748/7eb41121-879d-4d17-b6b9-8bd20cdad6dc)
![image](https://github.com/novuhq/novu/assets/83523748/93f2b39f-5400-4c8f-859e-0dd08a556b6b)
![image](https://github.com/novuhq/novu/assets/83523748/dece733b-54e8-4d75-b86f-bc059aa5f40b)

in in-app, vue/react are the same

### 👟 Reproduction steps

![image](https://github.com/novuhq/novu/assets/83523748/999edd72-5312-49ae-8abd-b20e1ac99ce8)
![image](https://github.com/novuhq/novu/assets/83523748/4346ea7a-e399-4af8-bfc7-7809d451e656)

### 👍 Expected behavior

Appear “Nothing new to see here yet”, Instead of going in circles

### 👎 Actual Behavior with Screenshots

![image](https://github.com/novuhq/novu/assets/83523748/3ebab9af-55ec-4a11-be50-a2189b32bbd9)

### Novu version

0.24.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by michaldziuba03** [comment]
1. Make sure that your subscriber exists (with given subscriberId)
2. Do you have [HMAC enabled](https://docs.novu.co/notification-center/client/react/get-started#enabling-hmac-encryption) (maybe by accident)? - if so, you need to pass subscriberHash generated on the server (or disable HMAC verification for now).
