### ISSUE TITLE
🐛 Bug Report: Tooltip not visible in workflow edit module

### ISSUE THREAD

**Issue by harshit078** [notifirehq/notifire#5831]
### 📜 Description

When Editing a step in workflow, Tooltip for Add Variant, Set Conditions, Delete is not visible and hidden. 

### 👟 Reproduction steps

1. Create a new workflow
2. Add a provider (SMS, Email, etc)
3.Edit Step
4. Hover over the top right 3 buttons

### 👍 Expected behavior

Tooltip should be visible

<img width="310" alt="Screenshot 2024-06-26 at 1 44 01 PM" src="https://github.com/novuhq/novu/assets/73997189/23bbbbfe-316b-48a7-a4e0-5ee2d0719059">

### 👎 Actual Behavior with Screenshots

Tooltip is not visible.

https://github.com/novuhq/novu/assets/73997189/f09dbc69-d6b8-4757-bc5a-7257dc5fe1d0

<img width="1792" alt="Screenshot 2024-06-26 at 1 57 35 PM" src="https://github.com/novuhq/novu/assets/73997189/b4dc76ca-004f-469d-8ba0-e5eb0d8ccdd1">

### Novu version

SelfHosted

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by AkshitSinghal224** [comment]
@jainpawan21 Hi team, I am interested on working on this issue can you assign it to me so that i can start working on it.

**Comment by jainpawan21** [comment]
@AkshitSinghal224 

Assigned this issue to you ✅

**Comment by AkshitSinghal224** [comment]
@jainpawan21 thank you for assisting this issue I will try to complete it by this weekend

**Comment by Anonymous961** [comment]
@jainpawan21 I think this issue has been fixed. I'm not facing this bug.
![image](https://github.com/user-attachments/assets/4e947a15-f445-43cf-a5ad-c633d5873117)

**Comment by jainpawan21** [comment]
@harshit078 Did you manage to reproduce this?

**Comment by AkshitSinghal224** [comment]
@jainpawan21 yeah for me it also fixed!
