### ISSUE TITLE
🐛 Bug Report: Can't get data from more than one feed 

### ISSUE THREAD

**Issue by stellistelli** [notifirehq/notifire#5885]
### 📜 Description

I try to call two different feeds, turns out, it only call one feed in the network.

### 👟 Reproduction steps

Let's Say, i have two feed identifier "govmart" and "trigger". 
I just need to call two different useFetchFunction inside the page. 
But the two useFetchFunction only return the first one useFetchFunction function that has been called. 

After trying to figure out, 
when i installed @novu/notification-center version 0.16.0 , it worked well
but i installed @novu/notification-center version >0.16.0, it didn't work well.

### 👍 Expected behavior

Govmart Feed : 
<img width="1512" alt="Screenshot 2024-06-30 at 21 38 42" src="https://github.com/novuhq/novu/assets/130949370/79beb086-d80c-46d4-824f-538a315d3b20">

Trigger Feed:  
<img width="1512" alt="Screenshot 2024-06-30 at 21 38 21" src="https://github.com/novuhq/novu/assets/130949370/23683af7-79fc-4a0c-a1ca-c661323f64a2">

### 👎 Actual Behavior with Screenshots

Govmart Feed : 
<img width="1512" alt="Screenshot 2024-06-30 at 21 39 42" src="https://github.com/novuhq/novu/assets/130949370/f5881ac5-cb38-4cec-a3a6-58cb9eed510d">

Trigger Feed : 
<img width="1512" alt="Screenshot 2024-06-30 at 21 38 48" src="https://github.com/novuhq/novu/assets/130949370/77f883c4-b3ee-4f5e-8b32-96e40a60fa94">

### Novu version

0.16.1

### npm version

10.5.0

### node version

20.12.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by jainpawan21** [comment]
Closing the issue as per [discord post](https://discord.com/channels/895029566685462578/1256182269744254997)
