### ISSUE TITLE
🐛 Bug Report: Web Component generate errors in the console in Angular app

### ISSUE THREAD

**Issue by MajaEffenberg** [notifirehq/notifire#6138]
### 📜 Description

When we load your Web Component: `notification-center-component` in our Angular app we always get these 3 errors in the console. They also reappear when the `notification-center-component` receives new notifications.

![image](https://github.com/user-attachments/assets/0f43c488-4349-48a4-956c-7a39c47693bc)

### 👟 Reproduction steps

We add to our Angular application `notification-center-component` as:

``` html
<notification-center-component
    [subscriberId]="subscriberId"
    [applicationIdentifier]="novuConfig.applicationId"
    [backendUrl]="novuConfig.backendUrl"
    [socketUrl]="novuConfig.wsUrl"
    [colorScheme]="'light'"
    [styles]="notificationStyles"
    [i18n]="'de'"
    [notificationClicked]="redirectOnNotificationClick()"
></notification-center-component>
```

When `notification-center-component` component is loaded or a new notification is received, errors are generated in the console.

### 👍 Expected behavior

It should not generate any errors or warnings. If warning is needed, it should not be generated as an error in the console.

### 👎 Actual Behavior with Screenshots

Error messages in the images above.

### Novu version

@novu/notification-center-angular: 2.0.0-canary.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by pawelmiklas** [comment]
I’m dealing with the same issue in vue app

**Comment by MajaEffenberg** [comment]
Is there any news about this bug?
