### ISSUE TITLE
🐛 Bug Report: Novu after Update not usable any more - stuck at auth/application

### ISSUE THREAD

**Issue by alexanderhofstaetter** [notifirehq/notifire#6144]
### 📜 Description

After upgrading to the latest version of novu (docker tag prod - as of today) we cannot log in because we are stuck at:

![image](https://github.com/user-attachments/assets/baeb544c-418d-450b-9d40-feac35d45c4e)

### 👟 Reproduction steps

1. Login
2. Stuck at Login

### 👍 Expected behavior

It should let me log in.

### 👎 Actual Behavior with Screenshots

no errors in network, no errors in console

### Novu version

novu selfhosted

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by vitoorgomes** [comment]
@alexanderhofstaetter had a terrible time with this problem as well today, don't know if you found any solution, but I found a solution.

In my case, im setting up my self hosted novu for the first time with k8s and i've made the same mistake to use the `prod` tag...

My solution was to set ALL pods to fetch the `0.24.0` image tag instead `prod`, so things started working

Each service would use something like
```
image: ghcr.io/novuhq/novu/api:0.24.0
image: ghcr.io/novuhq/novu/embed:0.24.0
image: ghcr.io/novuhq/novu/web:0.24.0
image: ghcr.io/novuhq/novu/widget:0.24.0
image: ghcr.io/novuhq/novu/worker:0.24.0
image: ghcr.io/novuhq/novu/ws:0.24.0
```

the only one that I didn't find the `0.24.0` tag (as of the day im writing this) was the `webhook` image, so currently i'm using `image: ghcr.io/novuhq/novu/webhook:prod` and seems to be working, but im very early on my tests and I cant be sure if it's everything ok

hope this helps you or someone else

**Comment by alexanderhofstaetter** [comment]
@SokratisVidros how can you close this as "not planned" - the feedback on the issues here from novu is terrible, and most of them simple do not get even an answer.

Far away from open source IMHO.

**Comment by SokratisVidros** [comment]
@alexanderhofstaetter, this tag came from an automatic integration we have with Linear.

We are in the process, of building our roadmap until the end of the year, including a new release for Novu V2 docker images that is planned to happen by the end of this month.

That being said, the pending v2.0 docker image release should address this and similar issues.

Using the latest `prod` image tag should also fix it but note that docker images with `prod` tag are used for Novu Cloud offering. They are not officially supported for on premise installation and are built multiple times a day.
