### ISSUE TITLE
🐛 Bug Report: Removal of Deprecated version Property from docker-compose.yml

### ISSUE THREAD

**Issue by sasselin** [notifirehq/notifire#6363]
* **I'm submitting a...**
  - [ ] bug report
  - [ ] feature request
  - [ ] question about the decisions made in the repository
  - [ ] question about how to use this project
* **Summary**
  Remove the version property from the docker-compose.yml file as it is deprecated and no longer required. The file originally specified version: '3.9', but this property is now considered unnecessary.
* **Other information**
  Removing the version property is based on Docker’s guidance that recent Compose versions do not require it explicitly. The modified docker-compose.yml includes multiple service configurations such as Redis, MongoDB, API, Worker, Web, etc. The key modification is removing the deprecated version property while keeping everything else intact.

**Comment by twentyone24** [comment]
https://github.com/novuhq/novu/pull/6387

**Comment by merrcury** [comment]
This fixed, closing this
