### ISSUE TITLE
🐛 Bug Report: Getting error in FCM V1 integration

### ISSUE THREAD

**Issue by binoytv9** [notifirehq/notifire#6567]
### 📜 Description

We've disabled the Cloud Messaging API (Legacy) API and we're using novu docker v0.23.0.

Getting below error:
"Sending message failed due to \"Operation is not implemented, or supported, or enabled. Raw server response: \"{\"error\":{\"code\":501,\"message\":\"Operation is not implemented, or supported, or enabled.\",\"status\":\"UNIMPLEMENTED\"}}\"\""

### 👟 Reproduction steps

Send PN
Get the above error in Activity log

### 👍 Expected behavior

Send PN without any error

### 👎 Actual Behavior with Screenshots

Getting below error
![image](https://github.com/user-attachments/assets/5bb53bfd-15c2-497e-92ad-b6d058ecde20)

### Novu version

v0.23.0

### npm version

10.2.3

### node version

v18.19.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by jainpawan21** [comment]
- update your `worker` and other services docker image tag to` 0.24.3`  except api service
- if you see below error with `api` tag `0.24.1 `and `0.24.2`. use API docker image tag `0.24.0`
```
 ✘ api Error manifest unknown                                                                    3.2s 
Error response from daemon: manifest unknown
```

Join our discord community :- https://discord.novu.co

**Comment by FilipSwiatczak** [comment]
@jainpawan21 
Can you please clarify if Novu supports later protocol than FCM v1?
Half way down in https://v0.x-docs.novu.co/channels-and-providers/push/fcm it says "Novu uses FCM version V1"
and FCM on account page states we should move to latest version of the protocol by 06/20/2024. 

We are running Novu v0.23.0 but on Docs for v2.0.0 I see the same Info box about FCM version 1. 
Attempting to send notifications to FCM in Novu results in:

`{
  "code": "messaging/unknown-error",
  "message": "An unknown server error was returned. Raw server response: \"<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That’s an error.</ins>\n  <p>The requested URL <code>/batch</code> was not found on this server.  <ins>That’s all we know.</ins>\n\". Status code: 404."
}`
Using same account json and deviceToken with a sample Go mockup (Firebase v3.13) works just fine

Happy to raise a new ticket if that helps?

**Comment by nandaborneo** [comment]
> [@jainpawan21](https://github.com/jainpawan21) Can you please clarify if Novu supports later protocol than FCM v1? Half way down in https://v0.x-docs.novu.co/channels-and-providers/push/fcm it says "Novu uses FCM version V1" and FCM on account page states we should move to latest version of the protocol by 06/20/2024.
> 
> We are running Novu v0.23.0 but on Docs for v2.0.0 I see the same Info box about FCM version 1. Attempting to send notifications to FCM in Novu results in:
> 
> `{ "code": "messaging/unknown-error", "message": "An unknown server error was returned. Raw server response: \"<!DOCTYPE html>\n<html lang=en>\n <meta charset=utf-8>\n <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n <title>Error 404 (Not Found)!!1</title>\n <style>\n *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n </style>\n <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n <p><b>404.</b> <ins>That’s an error.</ins>\n <p>The requested URL <code>/batch</code> was not found on this server. <ins>That’s all we know.</ins>\n\". Status code: 404." }` Using same account json and deviceToken with a sample Go mockup (Firebase v3.13) works just fine
> 
> Happy to raise a new ticket if that helps?

Hi, Did you manage to solved this for now ?
