### ISSUE TITLE
🐛 Bug Report: novu/api:0.24.3 missing node_modules deps

### ISSUE THREAD

**Issue by healdropper** [notifirehq/notifire#6573]
### 📜 Description

ghcr.io/novuhq/novu/api:0.24.3 seems to miss module '@novu/shared/utils in the official image to selfhost it

### 👟 Reproduction steps

- Upgrade image from 0.24.0 (working)  to 0.24.3 (failing)
-  Container will show "Cannot find module '@novu/shared/utils' in "/usr/src/app/node_modules/.pnpm/@novu+node@0.24.2/node_modules/@novu/node/build/main/index.js"

### 👍 Expected behavior

- 0.24.3 apì image should contain the required dependency@version and container should become ready

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/049d7237-79cd-485c-815c-63063180d01a)

### Novu version

0.24.3 (api)

### npm version

NA

### node version

NA

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by Muzammil-Yernal** [comment]
Any solution for this issue? I am facing the same problem, I am deploying novu on OpenShfit.

**Comment by wh1337** [comment]
Roll back to 0.24.0 and it should work, atleast until v2 is released

**Comment by Muzammil-Yernal** [comment]
> Roll back to 0.24.0 and it should work, atleast until v2 is released

Thanks for the update, I did revert to 0.24.0 yesterday and it worked!

**Comment by healdropper** [comment]
> Roll back to 0.24.0 and it should work, atleast until v2 is released

Sadly it is not a solution for my case since version 0.24.3 contained a fix to address problems with  android push notifications and Firebase.

**Comment by jainpawan21** [comment]
> > Roll back to 0.24.0 and it should work, atleast until v2 is released
> 
> Sadly it is not a solution for my case since version 0.24.3 contained a fix to address problems with android push notifications and Firebase.

@healdropper 

use 0.24.0 image for API and 0.24.3 for rest other services. 

You will not get this error and FCM push issue will be fixed
