### ISSUE TITLE
🚀 Feature: Button UI is Looking Good on Hover, It can be better

### ISSUE THREAD

**Issue by Raja-Abrar-Khan** [notifirehq/notifire#6603]
### 🔖 Feature description

The button on hover give the bad ui it can be better if fixed properly . The UI will improve and it will give better experience to the user.

### 🎤 Why is this feature needed ?

![Screenshot 2024-10-02 002155](https://github.com/user-attachments/assets/631ef1e6-6b10-4c51-93c3-a9392a9a6fb5)
![Screenshot 2024-10-02 002206](https://github.com/user-attachments/assets/950f7a10-b302-4267-8a62-24683f46a8dd)
![Screenshot 2024-10-02 002212](https://github.com/user-attachments/assets/ca4d8052-712d-422f-86f6-a5a44da07759)

### ✌️ How do you aim to achieve this?

I will Achieve this By Making the Button hover effect suit better according to the color combination and right now it looks like it is designed by the person who just learned what hover is . 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Raja-Abrar-Khan** [comment]
Assign me this issue

**Comment by shvmdev** [comment]
Hi, I'd like to work on this issue, can you assign it to me.

**Comment by tejodeepmitraroy** [comment]
Hi, I'd like to work on this issue.

**Comment by michaldziuba03** [comment]
Can you explain what exactly is wrong with the current design?

**Comment by jainpawan21** [comment]
@Raja-Abrar-Khan 

Can you share may be screen recording on how should hover effect look like?

**Comment by Raja-Abrar-Khan** [comment]
@jainpawan21  Sure , Let me make this first ,if you find it better then  i will make a pr

**Comment by janu12345678** [comment]
Hi, I'd like to work on this issue. On Hover, we can add animations to make the buttons interactive using some of the following techniques:
1. Color Transition
2. Gradient Animation
3. Sliding Icon
4. Border Animation/ Text Hover Effect
