### ISSUE TITLE
🚀 Feature: Add return types to @novu/node

### ISSUE THREAD

**Issue by KamalAman** [notifirehq/notifire#6611]
### 🔖 Feature description

It seems like @novu/node returns `AxiosResponse<any, any>` for all of the network requests. [Subscriber.ts](https://github.com/novuhq/novu/blob/next/packages/node/src/lib/subscribers/subscribers.ts)

Can we get it to be with proper return types?

Your api is well documented https://docs.novu.co/api-reference/subscribers/get-subscriber.

### 🎤 Why is this feature needed ?

I need proper types when developing or else everything goes to hell. 

### ✌️ How do you aim to achieve this?

You should be able to return codegen to generate all of the response types and the methods as well

I've used hay-api before, and its really simple: https://heyapi.vercel.app/openapi-ts/get-started.html
Just hook this script into your build process, it will generate a `services.gen.ts` with proper types. It'll generate the .ts. api based your openapi schema. Call those functions instead of axios directly.  

```
import { defineConfig } from '@hey-api/openapi-ts';

export default defineConfig({
  client: '@hey-api/client-fetch',
  input: 'path/to/openapi.json',
  output: 'libs/node/src/generated',
}); 
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by pritam0721** [comment]
@KamalAman can I work on these ?

**Comment by KamalAman** [comment]
Yeah for sure! Let me know if you need any feedback, but once you select the codegen, the rest should be pretty easy to just call the appropriate method. You will probably want to keep the fetcher standardized to axios.

**Comment by jainpawan21** [comment]
@KamalAman 

Thanks for the feedback. I agree, node sdk should have types as well. We are working on this.

**Comment by jainpawan21** [comment]
> @KamalAman can I work on these ?

@pritam0721 

I would recommend you to look into other issues, as it will be handled by our team

**Comment by pritam0721** [comment]
@jainpawan21 thank you for the info man and I wil .
