### ISSUE TITLE
🐛 Bug Report: @novu/js - Updating the read state of a Notification results in an empty instance

### ISSUE THREAD

**Issue by gtnsimon** [notifirehq/notifire#6631]
### 📜 Description

Hello,

With an `InApp` notification created with the `data` (https://docs.novu.co/sdks/framework/typescript/steps/inbox) key inside, updating the read state (using `notification.read()` or `notification.unread()`) results to an empty Notification instance.

### 👟 Reproduction steps

Front-end reproduction (with samples Workflows to reproduce the issue): https://stackblitz.com/edit/sb1-gov1vt?file=main.js

```js
// taken from the Stackblitz repro for quick review
import { Novu } from '@novu/js';

const novu = new Novu({
  subscriberId: import.meta.env.VITE_NOVU_SUB_ID,
  applicationIdentifier: import.meta.env.VITE_NOVU_APP_ID,
  backendUrl: 'https://api.novu.co',
  socketUrl: 'https://ws.novu.co',
});

const notifications = await novu.notifications.list();
const [notificationToUpdate] = notifications.data.notifications ?? [];
const updatedNotification = await notificationToUpdate.read();

console.log('updatedNotification', updatedNotification);
```

### 👍 Expected behavior

This is a valid Notification instance with data inside:

<img width="531" alt="image" src="https://github.com/user-attachments/assets/7c77a8e1-3599-45ee-af85-9f3192b53959">

### 👎 Actual Behavior with Screenshots

This is bad Notification instance with no data inside:

<img width="722" alt="image" src="https://github.com/user-attachments/assets/88326583-e06d-4bd6-a064-fca437db077a">

### Novu version

Novu SaaS

### npm version

NA

### node version

NA

### 📃 Provide any additional context for the Bug.

The Novu API response when calling `https://api.novu.co/v1/inbox/notifications/<NOTIFICATION_ID>/read` returns the following payload:

<img width="562" alt="image" src="https://github.com/user-attachments/assets/464885cc-ade5-46e0-9bff-23ef975fd02a">

No `data` key exists and I think this is the root cause. The `@novu/client` reads the `.data` key from `response.json()` to create a Notification which overlaps with `Notification.data` definition (https://docs.novu.co/sdks/framework/typescript/steps/inbox):

https://github.com/novuhq/novu/blob/e900c02d0842a97f6e488abfb2c3e189af0fbeb8/packages/client/src/http-client/http-client.ts#L83

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by mohdishaq786** [comment]
@gtnsimon  i want to work on this issue can you please assign me this issue

**Comment by jainpawan21** [comment]
@gtnsimon 

Thanks for sharing the bug. I can reproduce the issue.

**Comment by jainpawan21** [comment]
> @gtnsimon i want to work on this issue can you please assign me this issue

@mohdishaq786 We appreciate your interest in contribution. As this is a high priority bug, our team will fix this as early as possible.

**Comment by jainpawan21** [comment]
@gtnsimon 

We just fixed this issue. Can you please recheck this? Feel free to update in this thread if you are still seeing the old behavior.

**Comment by Omicrxn** [comment]
Hi! This is happening as of latest version of @novu/js 3.9.3 but with **archived** notifications, if i have notifications and i `archiveAll()` then i get an empty array when i `list()` or `list({archived:true})`. This issue only happens if i call `list()` after calling `archiveAll()` where it returns an empty array if i refresh the page and call `list()` it is correctly fetched.
