### ISSUE TITLE
🐛 Bug Report: Novu/js CORS IN LOCALHOST AFTER RUN DOCKER COMPOSE 

### ISSUE THREAD

**Issue by bekmarc** [notifirehq/notifire#6675]
### 📜 Description

The bug happen after i luanch docker compose and in angular i install Novu/Js for more customization, but i got unexcpeted Error  

"Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur http://localhost:3000/v1/inbox/session. Raison : l’en-tête « novu-api-version » n’est pas autorisé d’après l’en-tête « Access-Control-Allow-Headers » de la réponse de pré-vérification des requêtes CORS."

### 👟 Reproduction steps

1 Install angular 18
2  install Novu/Js
3 Launch Novu dockser compôse community
4 Configure it (follow https://docs.novu.co/inbox/headless/get-started)
5 and after ng serve you got "cors origins error "

### 👍 Expected behavior

It should work without cors error

### 👎 Actual Behavior with Screenshots

![Screenshot 2024-10-10 201302](https://github.com/user-attachments/assets/68517a94-01df-4251-a660-fb5675e896d6)

### Novu version

Self-hosted

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by dmitrydrynov** [comment]
I think this issue has a common problem with this one
https://github.com/novuhq/novu/issues/6644

**Comment by doanthai** [comment]
@bekmarc What do you use novu-api image docker version? Please use tag 2.0.0, novu-api allow all origin if use set `NODE_ENV` is test or local.
See code at [here](https://github.com/novuhq/novu/blob/v2.0.0/apps/api/src/config/cors.config.ts)

**Comment by bekmarc** [comment]
i fix issue after i change all image tag in docker compose to latest and launch "docker-compose up -d" for community file and evrything OK🪄

**Comment by bekmarc** [comment]
i fix issue after i change all image tag in docker compose to latest and launch "docker-compose up -d" for community file and evrything OK🪄

**Comment by iSuslov** [comment]
Seems like it is not fixed for when `API_CONTEXT_PATH` is set. I looked at latest version and url matching is [hardcoded](https://github.com/novuhq/novu/blob/v2.1.1/apps/api/src/config/cors.config.ts). 

@scopsy could you please reopen
