### ISSUE TITLE
🚀 Feature: @novu/framework support for commonjs modules

### ISSUE THREAD

**Issue by paulwer** [notifirehq/notifire#6701]
### 🔖 Feature description

Add .cjs modules into the build of the packages.

### 🎤 Why is this feature needed ?

Currently the packages are not supporting commonjs, which is still widly used.

### ✌️ How do you aim to achieve this?

f.ex. https://stackoverflow.com/questions/74937600/how-to-support-es-modules-and-commonjs-modules-at-the-same-time

### 🔄️ Additional Information

maybe this would also be helpfull for other packages.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by rifont** [comment]
Resolved with the new release of `@novu/framework`@[2.4.0](https://www.npmjs.com/package/@novu/framework/v/2.4.0) with both ESM+CJS bundled into build artifacts 🎉
