### ISSUE TITLE
🚀 Feature: Provide own tunnel when utilizing Local Studio

### ISSUE THREAD

**Issue by wh1337** [notifirehq/notifire#6709]
### 🔖 Feature description

Add the ability to pass a command to `npx novu dev` that will not start the automatic local tunnel. This flag would should take in a string argument that would be a user provided tunnel.

Example:

`npx novu dev --tunnel https://my-local-tunnel.ngrok.io`

### 🎤 Why is this feature needed ?

In a corporate environment, some domains and URLs are blocked by the company firewall. My utilizing, for example, ngrok, I would be able to use our corporate approved tunnel thus complying with our internal netsec standards.

### ✌️ How do you aim to achieve this?

Run `npx novu dev --tunnel https://my-local-tunnel.ngrok.io`, the Novu provided local tunnel would not start, instead would utilize the provided url.

### 🔄️ Additional Information

After speaking with Dima, I would like to attempt to resolve this.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by rifont** [comment]
This is now released in `novu`@[2.1.0](https://www.npmjs.com/package/novu/v/2.1.0) 🎉

![image](https://github.com/user-attachments/assets/c86f5f62-aa79-4fa7-9391-c97425134653)
