### ISSUE TITLE
🐛 Bug Report: Local Studio doesn't authenticate itself after signing into the dashboard

### ISSUE THREAD

**Issue by wh1337** [notifirehq/notifire#6710]
### 📜 Description

1. When you go to `http://localhost:2022/studio/onboarding/preview` and after signing in, you get 401 errors when trying to authenticate against the hosted Novu api.
2. When trying to trigger a workflow from the studio onboarding, error messages appear stating that the Api Key cannot be found, even though `NOVU_SECRET_KEY` is in the env. Tried exporting this to my system env vars and it still failed.

Current implementation use express middleware in a nestjs project:

```ts
	app.use(express.json())
	app.use('/api/novu', serve({
		workflows: [AlertWorkflow],
		client: new Client({
			strictAuthentication: false
		})
	}))
```

### 👟 Reproduction steps

re description

### 👍 Expected behavior

Should be authenticated and should trigger test workflows.

### Image 1: Screenshot of the failed validation against the Novu API
![2024-10-16 at 21 47 18@2x](https://github.com/user-attachments/assets/c72cdb48-404d-458a-80a0-337131686364)

### Image 2: Failed attempt to trigger
![2024-10-16 at 21 54 37@2x](https://github.com/user-attachments/assets/37ea116a-f7c4-4f16-823c-e5426a055a5d)

### Novu version

Novu SaaS

### node version

20 LTS

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by wh1337** [comment]
Workaround: Manually go to `http://localhost:2022/studio/flows` if the onboarding fails you

**Comment by L-U-C-K-Y** [comment]
> Workaround: Manually go to `http://localhost:2022/studio/flows` if the onboarding fails you

After going to the URL manually, I still get 401 issues, do you have the same?

<img width="1162" alt="SCR-20241020-lvtt" src="https://github.com/user-attachments/assets/0fc0ef82-9728-4cd5-8605-45b7e0006f6f">

**Comment by jainpawan21** [comment]
Add this environment variable `NOVU_API_URL` in bridge application, and change the value as per your configuration.
```
NOVU_API_URL=http://localhost:3000
```

**Comment by L-U-C-K-Y** [comment]
> Add this environment variable `NOVU_API_URL` in bridge application, and change the value as per your configuration.
> 
> ```
> NOVU_API_URL=http://localhost:3000
> ```

Thanks @jainpawan21 for the great help!

In terms of the syncing, I was able to solve it with this command:

```bash
npx novu@latest sync \
  --bridge-url <> \
  --api-url <> \
  --secret-key <>
```

**Comment by QusaiKhalid** [comment]
> Add this environment variable `NOVU_API_URL` in bridge application, and change the value as per your configuration.
> 
> ```
> NOVU_API_URL=http://localhost:3000
> ```

After I did this I am still getting error 500



Failed to load resource: the server responded with a status of 404 (Not Found)
:4000/api/novu?actio…-onboarding-email:1 
 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
main.d8f07daa.js:8 Uncaught (in promise) 
Mk
code
: 
"ERR_BAD_RESPONSE"
config
: 
{transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}
message
: 
"Request failed with status code 500"
name
: 
"AxiosError"
request
: 
XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
response
: 
{data: {…}, status: 500, statusText: 'Internal Server Error', headers: sE, config: {…}, …}
stack
: 
"AxiosError: Request failed with status code 500\n    at http://localhost:4200/static/js/main.d8f07daa.js:8:5130382\n    at XMLHttpRequest.h (http://localhost:4200/static/js/main.d8f07daa.js:8:5130530)\n    at TE.request (http://localhost:4200/static/js/main.d8f07daa.js:8:5136131)\n    at async i (http://localhost:4200/static/js/main.d8f07daa.js:8:5280156)"
[[Prototype]]
: 
Error
