### ISSUE TITLE
Bug: ITheme and ITriggerPayload throws type errors with strict mode enabled

### ISSUE THREAD

**Issue by laurynas-wn** [notifirehq/notifire#68]
- **I'm submitting a ...**
  [ x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Calling `const notifire = await new Notifire()` with Typescript strict mode enabled causes type errors.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Affected types are `ITriggerPayload` and `ITheme` Something like this fixes the problem:

```
export interface ITheme {
    branding: {
        mainColor?: string;
        logo?: string;
    } & CustomBranding
    emailTemplate: IEmailTemplate;
}
interface CustomBranding {
    [key: string]: string;
}
```

Errors:

```
node_modules/@notifire/core/build/main/lib/template/template.interface.d.ts:17:5 - error TS2411: Property '$email' of type 'string | undefined' is not assignable to 'string' index type 'string | number | boolean'.

17     $email?: string;
       ~~~~~~

node_modules/@notifire/core/build/main/lib/template/template.interface.d.ts:18:5 - error TS2411: Property '$phone' of type 'string | undefined' is not assignable to 'string' index type 'string | number | boolean'.

18     $phone?: string;
       ~~~~~~

node_modules/@notifire/core/build/main/lib/template/template.interface.d.ts:20:5 - error TS2411: Property '$theme_id' of type 'string | undefined' is not assignable to 'string' index type 'string | number | boolean'.

20     $theme_id?: string;
       ~~~~~~~~~

node_modules/@notifire/core/build/main/lib/theme/theme.interface.d.ts:3:9 - error TS2411: Property 'mainColor' of type 'string | undefined' is not assignable to 'string' index type 'string'.

3         mainColor?: string;
          ~~~~~~~~~

node_modules/@notifire/core/build/main/lib/theme/theme.interface.d.ts:4:9 - error TS2411: Property 'logo' of type 'string | undefined' is not assignable to 'string' index type 'string'. 

4         logo?: string;
        ```

**Comment by DamsithKarunaratna** [comment]
@laurynas-wn Your approach is correct. The contention between types comes from declarations like this, where `$theme_id?: string;` which translates to "_string | undefined_" conflicts with `[key: string]: string | boolean | number;`
https://github.com/notifirehq/notifire/blob/f45886f452a34b2f6137d5083282e4274dd3139e/packages/core/src/lib/template/template.interface.ts#L21-L27

If the intention is to allow additional properties to be defined, what you have come up with is the way to go 😊. Either that, or use a utility class like Record.

```
type ITriggerPayload = {
  $email?: string;
  $phone?: string;
  $user_id: string;
  $theme_id?: string
} & Record<string, string | boolean | number>
```

which will allow something like this to be created

```
const test: ITriggerPayload = {
    $user_id: "some-user-id",
    additionalProperty1: "",
    additionalProperty2: 1,
    additionalProperty4: false,
}
```
