### ISSUE TITLE
🚀 Feature: <Inbox /> filter preferences by tags

### ISSUE THREAD

**Issue by paulwer** [notifirehq/notifire#6832]
### 🔖 Feature description

We are currently looking into using the <Inbox /> components and are looking for the ability to filter workflows f.ex. by tags.

### 🎤 Why is this feature needed ?

We have some workflows, which are for internal personal, which should be able to set preferences, but which are not used outside of our organization.

### ✌️ How do you aim to achieve this?

Eigher by new backend functionality or by a filter method just in the Inbox component.
When implemented by tag-filter, may considder doing it in a way like the tabs for the workflows.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by ComBarnea** [comment]
Hi @paulwer I think you might be looking for this (https://docs.novu.co/inbox/react/components/inbox#filter-visible-preferences), can you verify if this is it, or something else?

**Comment by paulwer** [comment]
@ComBarnea thanks, thats it, we missed that section.
