### ISSUE TITLE
🐛 Bug Report: Next 15 fails to build with Novu serve()

### ISSUE THREAD

**Issue by jklinehamer** [notifirehq/notifire#6881]
### 📜 Description

Trying to build for production

### 👟 Reproduction steps

1. Install Novu with a Next 15 app as described in the Novu setup guide
2. Create the route handler using Novu's serve() function as explained in the docs
3. Try building your app

### 👍 Expected behavior

Build successfully

### 👎 Actual Behavior with Screenshots

Fails to compile
![CleanShot 2024-11-07 at 03 20 22](https://github.com/user-attachments/assets/24438420-da0e-4691-9ad1-37ebfb77543f)

### Novu version

Novu SaaS

### 📃 Provide any additional context for the Bug.

After NextJS 15 the typing changed for Route Handlers. The second argument is now of type "RouteContext", which causes this error.

Inngest, another open source project with very similar structure to Novu, has resolved the issue for their product. The relevant source code from Inngest (and how they fixed the issue) can be found here: https://github.com/inngest/inngest-js/blob/main/packages/inngest/src/next.ts

Using their source I was able to create a custom Novu serve() function and get this working, but it would be nice to have this out-of-the-box with Novu.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by rifont** [comment]
Thanks for reporting. We will be releasing a fix for this today.

**Comment by rifont** [comment]
Support for Next.js 15 + Turbopack dev (`next dev --turbo`) is now available with `@novu/framework`@[2.4.0](https://www.npmjs.com/package/@novu/framework/v/2.4.0) 🎉
