### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by ssoronid** [notifirehq/notifire#7282]
### 📜 Description

It bugs out when I try to call novu.preferences.update...

im using 

    "@novu/js": "^2.6.3",

and having this issue, while lists functions perfectly, update is not:

```
TypeError: novuClient.preferences.update is not a function

Source
src\context\NotificationsContext.tsx (217:36) @ update

  215 |     
  216 |     try {
> 217 |       await novuClient.preferences.update({
      |                                    ^
  218 |         workflowId: workflowId || undefined, // If no workflowId, it updates global preferences
  219 |         channelPreferences, // This matches Novu's expected format
  220 |       });
 
  ```

### 👟 Reproduction steps

Create a novu client like this:
```
      const novu = new Novu({
        subscriberId: subscriberId,
        applicationIdentifier: process.env.NEXT_PUBLIC_NOVU_APP_ID!
      });
      
      setNovuClient(novu);
```

Then if we call list, it works:

```
        const response = await novuClient.preferences.list();
        return response.data || [];
        ```
        
        But update is not:
        
        ```
        TypeError: novuClient.preferences.update is not a function

Source
src\context\NotificationsContext.tsx (217:36) @ update

  215 |     
  216 |     try {
> 217 |       await novuClient.preferences.update({
      |                                    ^
  218 |         workflowId: workflowId || undefined, // If no workflowId, it updates global preferences
  219 |         channelPreferences, // This matches Novu's expected format
  220 |       });
  ```

### 👍 Expected behavior

it should be at least in the function as stated in the doc

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/e4fbca3d-d317-466f-8a89-c85614ff7cc1)

### Novu version

    "@novu/js": "^2.6.3",

### node version

20.9.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by fkiptooh-r** [comment]
Hi @ssoronid just experienced the same bug too, any response or solution concerning this bug will be highly appreciated.

**Comment by ssoronid** [comment]
Hi! I didn't see any interests into guide me in the right direction and doesn't have the experience yet collaborating on PRs but I'm still in need to get this fixed... So I can Collaborate into proposing a fix.

In the meantime I think I should call another method to tackle this, but it's getting too mixed and out of our usecase that I'm thinking about making a simpler approach with a custom solution.

**Comment by SokratisVidros** [comment]
Thank you for reporting this.

This is a typo in our docs. In `@novu/js` you can update preferences individually via the [preference.update](https://github.com/novuhq/novu/blob/bd2f04dee4aec8014298bb9072c7894406c369c5/packages/js/src/preferences/preference.ts#L45) method.

We've just pushed a fix to the docs.

**Comment by SokratisVidros** [comment]
Do you have a use case where you want to update multiple preferences across workflows at once? If yes, we can convert this to a feature request.
