### ISSUE TITLE
📚 Docs Feedback: Unable to build a workflow according to Quickstart

### ISSUE THREAD

**Issue by Lexachoc** [notifirehq/notifire#7368]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://docs.novu.co/getting-started/quickstart#create-a-new-workflow
https://docs.novu.co/workflow/how-to/build-a-workflow

### Kind of issue

Missing information

### Issue description

I followed the documentation: https://docs.novu.co/getting-started/quickstart#create-a-new-workflow
and https://docs.novu.co/workflow/how-to/build-a-workflow

![image](https://github.com/user-attachments/assets/bf5967ab-76cb-49bc-bf7e-82a2f585418a)

But there's no **Create Workflow** button in the dashboard!

![image](https://github.com/user-attachments/assets/8a33d8c7-0d35-4047-bf9d-e4a3ff43dc4f)

I realized that I got this view because I received a 14-day trial immediately after logging in and creating an organization.

But it's confusing because I don't know how to proceed because the description and the dashboard view don't match.

Am I missing something or should the documentation be updated?

Thank you.

**Comment by Lexachoc** [comment]
I switched to the beta dashboard v2, the button is there!

![image](https://github.com/user-attachments/assets/03c70565-ef13-4480-8acc-abb8b95f93a9)

**Comment by scopsy** [comment]
Great! Sorry for the confusion 🙏

**Comment by bakert** [comment]
I just encountered this. It's pretty confusing that almost the very first thing the Quickstart instructions tell you to do is not possible. I also switched to the v2 Beta dashboard and got the button, thanks to this ticket.
