### ISSUE TITLE
Create NestJS module wrapper

### ISSUE THREAD

**Issue by ComBarnea** [notifirehq/notifire#74]
### I'm submitting a ...
-  feature request

### Summary
Add a module for [NestJS](https://nestjs.com/), for nice and easy usage within NestJs based code-bases.

#### Module API
The initialization module should create a notifire instance registered with providers and templates. Accessing the module at a later stage should allow adding more templates and providers at run time.

```typescript
import { NotifireModule } from "@notifire/nest";

@Module({
  imports: [
    NotifireModule.forRoot({
      providers: [
        new SendgridEmailProvider({
          apiKey: process.env.SENDGRID_API_KEY,
          from: "sender@mail.com",
        }),
      ],
      templates: [
        {
          id: "password-reset",
          messages: [
            {
              subject: "Your password reset request",
              channel: ChannelTypeEnum.EMAIL,
              template: `
          Hi {{firstName}}!
          
          To reset your password click <a href="{{resetLink}}">here.</a>
          
          {{#if organization}}
            <img src="{{organization.logo}}" />
          {{/if}}
      `,
            },
          ],
        },
      ],
    }),
  ],
})
export class CustomerModule {}
```

### Injectable notifire instance
And `@Injectable` singleton service should be accessible in other nestjs services and modules.
```typescript
@Injectable()
class UserService {
   constructor(private notifire: Notifire) {

   }

  async triggerEvent() {
      await this.notifire.trigger(.....)
   }
}
```

The new module can be added to `packages/nest` folder. Boilerplate for the package can be taken from running `yarn run generate:provider` and then copying the folder to the packages folder.

**Comment by devblin** [comment]
Hey, I would like to work on this issue if it's unassigned, and would like to know more.

**Comment by scopsy** [comment]
Hi, @devblin sure thing! 

Basically, we want to create a nestjs root module that will allow registering provider and templates easily (It should call the appropriate methods from the notifire/core library).
And we also should expose an Injectable of the `notifire` library instance to allow an easy trigger.

Let me know if you need more specific API design, or you can also prepare a draft PR with your thoughts of it and we can elaborate from there :)

**Comment by devblin** [comment]
@scopsy , Hey thank you for assigning this issue to me.
And, if `notifire` follows specific API design I would like to know more.

**Comment by scopsy** [comment]
@devblin Sure, I'll try to provide more information until tomorrow.

**Comment by scopsy** [comment]
@devblin Updated the issue description with API proposal. Let me know what you think about it

**Comment by devblin** [comment]
@scopsy , Hey thanks for the updated, the proposal is clear to me, and also I have been going through nestjs doc. for dynamic modules, so I will start the implementation soon, and will let you know for doubts.

**Comment by scopsy** [comment]
@devblin Amazing! Feel free to join us on discord and ask for help if you need it 🙏

**Comment by davidsoderberg** [comment]
This one can be closed?

**Comment by scopsy** [comment]
@davidsoderberg Yep!
