### ISSUE TITLE
Add new SendinBlue provider

### ISSUE THREAD

**Issue by ComBarnea** [notifirehq/notifire#79]
### What?
New [SendinBlue](https://github.com/sendinblue/APIv3-nodejs-library) Email Provider

### Why?
To have the ability to use [SendinBlue](https://github.com/sendinblue/APIv3-nodejs-library) as a provider.

### How?
Add new provider based on [this guide](https://docs.notifire.co/docs/community/create-provider)

### Usage
Example for SendinBlue provider registration needs to be finalized.

```ts
await notifire.registerProvider(
  new SendinBlueProvider({
    apiKey: process.env.SENDINBLUE_API_KEY
  })
);
```

**Comment by galezra** [comment]
I'd like to try this issue :)

**Comment by scopsy** [comment]
Sure thing! Assigned you

**Comment by scopsy** [comment]
To get you started just run `yarn run generate:provider` from the root folder

**Comment by scopsy** [comment]
@galezra Merged 🎉🎉🎉
