### ISSUE TITLE
Suggestion: separate providers from core

### ISSUE THREAD

**Issue by themisir** [notifirehq/notifire#82]
- **I'm submitting a ...**
 [ ] bug report
 [x] feature request
 [ ] question about the decisions made in the repository
 [ ] question about how to use this project

- **Summary**
I think currently notifire core (pubsub system) and providers are all in the same package. I think to reduce bundle size and bloat-ness it would be great to separate providers to individual packages and make core package dependency independent.

```ts
import { Notifire } from '@notifire/core';
import { SomeProvider } from '@notifire/some-provider';

...
```

**Comment by scopsy** [comment]
Hi, @themisir ,

Currently, every provider has its own npm package `@notifire/sendgrid`, `@notifire/postmark` and etc...
So I believe that what you are suggesting already exists. 

Let me know if I missed something.

**Comment by themisir** [comment]
Oops, missed that. I thought providers are written inside core package (the examples on website imports them from core pkg). So it's alright. Keep it up 😇
