### ISSUE TITLE
Add new SNS provider

### ISSUE THREAD

**Issue by Wyfy0107** [notifirehq/notifire#86]
**Is your feature request related to a problem? Please describe.**
New SNS SMS Provider

**Describe the solution you'd like**
use the aws sdk: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SNS.html

**Describe alternatives you've considered**

**Additional context**

**Comment by scopsy** [comment]
I think that we can create a new sns provider with `AamazonSMSProvider` and later we can add to the same provider a `Push` provider aswell.

**Comment by Wyfy0107** [comment]
May I try with a pull request for this provider ?

**Comment by scopsy** [comment]
@Wyfy0107 Sure! Assigned you. Let me know if you need any help and feel free to join us on discord for any help: https://discord.gg/SDt3t9RT

**Comment by scopsy** [comment]
@Wyfy0107 To generate a new provider run : `yarn run generate:provider`. Didn't have the time to update the docs with it
