### ISSUE TITLE
Is this coding to read my text messages?

### ISSUE THREAD

**Issue by juniormiguel** [notifirehq/notifire#92]
I found this installed into my computer and I tried to learn coding but someone else is up loading stuff. What do I do lol

**Comment by juniormiguel** [comment]
I don't even know where to save the file of the codes to install an app.

**Comment by ComBarnea** [comment]
@juniormiguel would you care to elaborate on what seems to be the issue? this is a Github repo for Notifire. We don't accept issues that are unrelated. Please let me know if you require any assistance, have any ideas or suggestions.
