### ISSUE TITLE
Sendgrid attachments support

### ISSUE THREAD

**Issue by scopsy** [notifirehq/notifire#94]
## What?
Add support for sending attachments for our [Sendgrid](https://github.com/notifirehq/notifire/tree/master/providers/sendgrid) provider.

### Why?
To have the ability to use send attachments.

### How?
Based on Notifire IAttachmentOptions interface found [here](https://github.com/notifirehq/notifire/blob/master/packages/core/src/lib/template/template.interface.ts).
And Sendgrid methods found [here](https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/attachments.md)

### Usage
Based on Notifire IAttachmentOptions interface on the trigger.

**Comment by ComBarnea** [comment]
See relevant attachment methods at Sendgrid use-cases

### Single/multiple and inline
<img width="1036" alt="Screen Shot 2021-11-13 at 13 23 47" src="https://user-images.githubusercontent.com/8877285/141640669-186a4b01-c629-48cc-a6b2-7999ec3ff962.png">

**Comment by galezra** [comment]
I'd like to work on this issue

**Comment by scopsy** [comment]
😍 assigned you
