### ISSUE TITLE
Add missing functionality warning when attachments are not handled

### ISSUE THREAD

**Issue by scopsy** [notifirehq/notifire#96]
## What?
The `RootEmailProvider` should provide a `buildAttachments` function and it should run a `console.warn` that the method for the current provider is not implemented.

## Why?
For providers not supporting attachments, and for providers, we still don't add the attachments API to and warn message should be shown.

**Comment by davidsoderberg** [comment]
My proposal to implement this: https://github.com/davidsoderberg/notifire/commit/8ab0db6c9e7149e7beb08f7b4ef94da2b645df5e

**Comment by scopsy** [comment]
@davidsoderberg This looks solid, but I was wondering, if we can create a parent class `RootEmailProvider ` we can extend from and override something like `getAttachments`, and all providers will need to implement this. If a provider have not implemented it will run the parent class which will print the warn message. Wdyt?

**Comment by davidsoderberg** [comment]
I think my implementation is cleaner... I do not see the need for a parent class right now more then maybe solve the problem my code already solves.

**Comment by scopsy** [comment]
@davidsoderberg Totally agree with you about the root class. I'm just thinking about the need in every provider to add this flag **and** the attachments logic. Instead of just adding the attachments logic and all the warnings will run automatically. 

Or maybe we can push forward and implement all of the current providers in `v.0.3.0`. And if a single provider does not support attachments he can `warn` about it in the provider implementation itself.

Anyways the supported attachments flag is meant to be temporary. 

Wdyt?

**Comment by davidsoderberg** [comment]
I think my flag is the most progressive way to not need to implement it in every provider and when all have it implemented we can remove it :)

**Comment by scopsy** [comment]
Got ya, so let's just start implementing the current providers in `v0.3.0`, and if we see it takes too much time we can fall back to your idea of adding the flags if we will plan to release 0.3 without all the providers supporting this.

I'll put this issue on hold for now, and we will try to get some help from all the providers, Looks like we have 7 of them so it's not that bad.

We can post this on discord maybe some people will help :)

**Comment by davidsoderberg** [comment]
My impl of nodemailerprovider... Should I create new PR for that?

**Comment by scopsy** [comment]
@davidsoderberg Sure! Comment on the issue so I can assign you
