### ISSUE TITLE
Mailgun attachments support

### ISSUE THREAD

**Issue by scopsy** [notifirehq/notifire#97]
## What?
Add support for sending attachments for our [Mailgun](https://github.com/notifirehq/notifire/tree/master/providers/mailgun) provider.

### Why?
To have the ability to use send attachments.

### How?
Based on Notifire IAttachmentOptions interface found [here](https://github.com/notifirehq/notifire/blob/master/packages/core/src/lib/template/template.interface.ts).
And Mailgun methods found [here](https://github.com/mailgun/mailgun.js#methods)

### Usage
Based on Notifire IAttachmentOptions interface on the trigger.

**Comment by ComBarnea** [comment]
See relevant attachment methods at Mailgun README 
### Single attachment
<img width="848" alt="Screen Shot 2021-11-12 at 21 34 24" src="https://user-images.githubusercontent.com/8877285/141525201-de6f8ff1-a7e8-43ec-8d9f-b4d02d0e2251.png">

### Multiple attachments
<img width="845" alt="Screen Shot 2021-11-12 at 21 34 30" src="https://user-images.githubusercontent.com/8877285/141525217-e563db75-90a0-4a44-9e3b-8af7d8be7e50.png">

### Inline Image
<img width="852" alt="Screen Shot 2021-11-12 at 21 34 37" src="https://user-images.githubusercontent.com/8877285/141525227-d02c4cdd-6cda-4588-96ae-b2ea634b3d29.png">

### Named attachment
<img width="818" alt="Screen Shot 2021-11-12 at 21 35 03" src="https://user-images.githubusercontent.com/8877285/141525182-60b9d171-0137-4c9e-b080-cedb5cc27e5e.png">

**Comment by l0ne** [comment]
I can take a look :)

**Comment by scopsy** [comment]
@l0ne you can create your branch out of `v0.3.0` branch and create a PR back to it so you can have the needed interface 🙌🚀

**Comment by scopsy** [comment]
We currently only do multiple attachments, we will deal with inline-attachments in later stage.
