### ISSUE TITLE
Postmark attachments support

### ISSUE THREAD

**Issue by scopsy** [notifirehq/notifire#99]
## What?
Add support for sending attachments for our [Postmark](https://github.com/notifirehq/notifire/tree/master/providers/postmark) provider.

### Why?
To have the ability to use send attachments.

### How?
Based on Notifire IAttachmentOptions interface found [here](https://github.com/notifirehq/notifire/blob/master/packages/core/src/lib/template/template.interface.ts).
And Postmark methods found [here](https://github.com/wildbit/postmark.js/wiki/Email-sending)

### Usage
Based on Notifire IAttachmentOptions interface on the trigger.

**Comment by ComBarnea** [comment]
See relevant attachment methods

## Multiple attachments
<img width="935" alt="Screen Shot 2021-11-13 at 11 16 21" src="https://user-images.githubusercontent.com/8877285/141613384-a2a69d34-a37c-4dfc-972f-f0d3a9f2f76b.png">

## Inline attachment
<img width="930" alt="Screen Shot 2021-11-13 at 11 16 25" src="https://user-images.githubusercontent.com/8877285/141613397-345f7c9a-2ea3-4028-95bd-77feeab807ce.png">

**Comment by galezra** [comment]
@scopsy I'll take it on

**Comment by scopsy** [comment]
@galezra assigned 🎉 Thanks for all the effort in this release. Appreciate it a lot 🙏🙏
